<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BACKUPExhibitorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('exhibitors')->delete();

        \DB::table('exhibitors')->insert(array(
            0 =>
            array(
                'id' => 8,
                'name' => 'BENBRAHIM Nesrine',
                'email' => 'benbrahimnesrine20@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$didGYwDEdAgSITCegGAAfOMWF0feVkHNw1FBS.ypbUw6zT2jCXhQy',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-12 19:01:06',
                'updated_at' => '2025-05-12 19:01:06',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            1 =>
            array(
                'id' => 9,
                'name' => 'Othmane test',
                'email' => 'othmane1benaldi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$MMNQGdR68ugQCGRt1r4BuuHSFhz707WTJUlqqxWUTGGDQyg3jbLJy',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-15 13:48:42',
                'updated_at' => '2025-05-15 13:48:42',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            2 =>
            array(
                'id' => 12,
                'name' => 'Profiles Aluminium Du Maghreb  "TPR ALGERIE"',
                'email' => 'amel.berkani@profal-dz.com',
                'verified_at' => NULL,
                'password' => '$2y$12$auPSxgLe5BgbmSIYtWSgGuE6oxAShVfIYah8uMZprRjh/cBrWXwLO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-21 14:38:41',
                'updated_at' => '2025-05-21 14:38:41',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            3 =>
            array(
                'id' => 13,
                'name' => 'OXXO ALGERIE SPA',
                'email' => 'dhiyaedine.abdelbaki@oxxo.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$dMwoAWlUvCgFfHHY6V51bO7T1p/I8XYt9p4wxuAK2Hs6c0TEgPqD.',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 12:04:38',
                'updated_at' => '2025-05-22 12:04:38',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            4 =>
            array(
                'id' => 14,
                'name' => 'BUILDTEC SARL ',
                'email' => 'buildtecdz@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$O/Cvdn7.9ZKFwhBCiJ2PjeAQ8CT2OmUvPKrSsrkAcyAQjifoyJlaS',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 12:50:03',
                'updated_at' => '2025-05-22 12:50:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            6 =>
            array(
                'id' => 16,
                'name' => 'ALL STORES ALGERIE',
                'email' => 'cm@allstoresalgerie.com',
                'verified_at' => NULL,
                'password' => '$2y$12$j9T23u0p4u688cyDDd0qd.jyj7CZDuzY5.XcojyzVo0JilXY6O5XC',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 13:13:46',
                'updated_at' => '2025-06-02 09:33:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            7 =>
            array(
                'id' => 17,
                'name' => 'SARL EDOOR',
                'email' => 'kseba@energical.com',
                'verified_at' => NULL,
                'password' => '$2y$12$eVTZF9cVANLRJxh1XKnUAux9NUGKlhz3GrYDrb3di6pYem2UsFAiC',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 13:35:49',
                'updated_at' => '2025-06-09 10:21:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            8 =>
            array(
                'id' => 18,
                'name' => 'ADVANCED GLASS TECHNOLOGIES  "AGT SARL"',
                'email' => 'algeria.arkoub@advancedglass.cn',
                'verified_at' => NULL,
                'password' => '$2y$12$ioFWjEHiqHPHivBOzxFQCucT6PxiN24il5.iB707kfzSfDmFD2P/G',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 13:43:03',
                'updated_at' => '2025-05-26 09:33:56',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            9 =>
            array(
                'id' => 19,
                'name' => 'SARL ORANGE BLUE',
                'email' => 'erkut.kutlu12@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$MBJs8YM1t8IUo38oOnaJIeNsPeopm/mSSbetK.MVOcFMhMJ24r8wO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 13:46:17',
                'updated_at' => '2025-06-02 09:00:40',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            10 =>
            array(
                'id' => 20,
                'name' => 'Amazit Aluminium et PVC',
                'email' => 'amazit.etat@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ueSUUhSJq7LZb/nfKO/bS.95IZhXe2GWGu2U0O9UHFWrpVUN7BSg6',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 14:06:49',
                'updated_at' => '2025-05-24 07:04:17',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            11 =>
            array(
                'id' => 21,
                'name' => 'SARL H PVC INDUSTRIES',
                'email' => 'hpvcdirection@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$NlBYyjJvL41ughrfXx5ujOWGLfBuoocIpGFw590pcucIZT9EhIs62',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 14:20:29',
                'updated_at' => '2025-05-22 14:24:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            12 =>
            array(
                'id' => 22,
                'name' => 'PROLUXE',
                'email' => 'nassim.bouchefra@oxxo.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$ET/BZGaGyrELW0R3bgdhweK4yL/EB7Bggo7FZD7JMQ8kpd88HO.O.',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-22 14:23:24',
                'updated_at' => '2025-06-03 12:43:56',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            13 =>
            array(
                'id' => 24,
                'name' => 'PROFIPLAST',
                'email' => 'aouatef.aoufi@groupe-chiali.com',
                'verified_at' => NULL,
                'password' => '$2y$12$HIXZUf8imVBztOQ30ALJFeDkMTqLgKlVm.ND8a2VOwCjgb7d9q56O',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 08:48:39',
                'updated_at' => '2025-05-25 08:48:39',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            14 =>
            array(
                'id' => 25,
                'name' => 'ALGAL PLUS SARL',
                'email' => 'hichem.dekar@algalplus.com',
                'verified_at' => NULL,
                'password' => '$2y$12$JuS1HY5qJiM38nvGbsSkZefWK3MDvnfYXxm3J97bR9Pfwn2R9mk/G',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 09:01:47',
                'updated_at' => '2025-05-25 09:01:47',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            15 =>
            array(
                'id' => 26,
                'name' => 'ALIANE Hacene Fabrication de Profilés en PVC',
                'email' => 'sup.prod.ecoplast@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ojl2WUwxJiAG5gIue5CfFeBKbTESLRWfiXhVp8jYQ49O1X6jP5L5m',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 09:09:17',
                'updated_at' => '2025-05-25 09:09:17',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            16 =>
            array(
                'id' => 27,
                'name' => 'EURL HADDAD RAHIM',
                'email' => 'eurlhaddad1122@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Wx.ezxmzgh3lo3aSLdKPyOqj9W32yHsC39BTMK9aWbW8L1M93H2IK',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 09:15:02',
                'updated_at' => '2025-06-21 08:55:28',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            17 =>
            array(
                'id' => 28,
                'name' => 'ROTO FRANK',
                'email' => 'abderrahim.karaslimane@roto-frank.com',
                'verified_at' => NULL,
                'password' => '$2y$12$tj93EuVV96HGryE53jmz7OAAkvLmJ0zbszbggnpDVtsc92SlAqf32',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 09:16:35',
                'updated_at' => '2025-05-25 09:16:35',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            18 =>
            array(
                'id' => 29,
                'name' => 'ADOPEN ALGERIE',
                'email' => 'mohamed.boukhors@adopen-algerie.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$Kkm0vNQurKuN9kWZ05i9meADhQeoAuzswDTxqCkQMD7hoI53fpcPW',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 09:18:22',
                'updated_at' => '2025-06-02 15:01:44',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            19 =>
            array(
                'id' => 30,
                'name' => 'PANADUR ALGERIE',
                'email' => 'panadur6@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$0iYanivSFX5yUohCzWnYPO.07j2tHCNGR/jqU6Ei.2dgWas2OrPNK',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 11:09:29',
                'updated_at' => '2025-05-25 11:09:29',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            20 =>
            array(
                'id' => 32,
                'name' => 'KCPH SARL',
                'email' => 'sarlkcph@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$nJ4vfY.udk9Zbgpwj1SIzO7MMDnT9PVctburOqzevUviwF/8prqEC',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 11:14:10',
                'updated_at' => '2025-05-25 11:14:10',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            21 =>
            array(
                'id' => 33,
                'name' => 'CIPAL SARL ',
                'email' => 'samira.berkane@cipal-dz.com',
                'verified_at' => NULL,
                'password' => '$2y$12$JcQ7deK/.dQHTe3ivErsZ.UJTCOSMVVcxUkMIerFaE8J7RJ8Cl9e2',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 11:17:04',
                'updated_at' => '2025-05-25 11:17:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            22 =>
            array(
                'id' => 34,
                'name' => 'Royal Tigra',
                'email' => 'Royaltigra@hotmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$2.FbJL0vf91bet2stGrpjegpdFdSp8mJsoRPEHJ/ATb.8qomZBkwu',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 12:57:10',
                'updated_at' => '2025-05-25 12:57:10',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            23 =>
            array(
                'id' => 35,
                'name' => 'Dz Line',
                'email' => 'tfprofile19@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$CWNP00MZPLmYSU9VwIT7sepLWeDwnOGk7v9rNQQJB.VI4tjF.DvqS',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 12:59:23',
                'updated_at' => '2025-07-12 20:06:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            24 =>
            array(
                'id' => 36,
                'name' => 'Picoplastic',
                'email' => 'appro@picoplastic.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$Xw7sUhP0a1/3S49QzlZIl.2ErqQeXyC2AQhNfKQ1ZYXoK1aWssvzS',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:01:31',
                'updated_at' => '2025-05-25 13:01:31',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            25 =>
            array(
                'id' => 37,
                'name' => 'Leader Profile',
                'email' => 'commercial.samir@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$vsHdV8tpdnxyoFlFpcFMfOYLT7M/ym02xiSjwKNlt8ECFU3vxmq8m',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:02:16',
                'updated_at' => '2025-06-16 22:53:17',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            26 =>
            array(
                'id' => 38,
                'name' => 'Ammari Store SARL',
                'email' => 'contact@stores-ammari.com',
                'verified_at' => NULL,
                'password' => '$2y$12$NCUJuf4fRrxzqWnR9762meAOJUMf0HiTNzRop0l/5F8aznA3QonyG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:04:21',
                'updated_at' => '2025-07-27 11:17:48',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            27 =>
            array(
                'id' => 39,
                'name' => 'SCS Construction',
                'email' => 'sboucekkine18@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$HJp87Hlv37LoQ4mWqQZoyuE9KYM1sXOaNQRYkjhWXUAx67h9Rjxse',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:06:15',
                'updated_at' => '2025-06-04 08:54:48',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            28 =>
            array(
                'id' => 41,
                'name' => 'Générale Top Store SARL ',
                'email' => 'info@gtstor.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$Aig4UTQsgA1CKbFeC9Ty0O2IIPJXSRzRq.dM0NlvhPJAScOjQAMKG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:37:15',
                'updated_at' => '2025-05-25 13:37:15',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            29 =>
            array(
                'id' => 42,
                'name' => 'Rena Touabet EURL',
                'email' => 'r.touabet@rena-dz.com',
                'verified_at' => NULL,
                'password' => '$2y$12$aqOwkuuVJx9fEaEBQp3nLe9mW9RVQN2981OSHVyY2gsw6JXMiitgq',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:39:07',
                'updated_at' => '2025-05-25 13:39:07',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            30 =>
            array(
                'id' => 43,
                'name' => 'SARL Sofitex',
                'email' => 'Contact@sofitex.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$OnZKqmt7NyyuGWoGjGuxkuRlfI9VvMPvipkUPt0plZplI7VVbNGeG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:41:00',
                'updated_at' => '2025-06-04 10:23:50',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            31 =>
            array(
                'id' => 45,
                'name' => 'Profilam PVC',
                'email' => 'profilampvc@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Y8bAl48Mr8gepn.hdxCsNeY9r.fQz/gqKUr99vceennNmvAzEunuC',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-25 13:43:58',
                'updated_at' => '2025-05-27 14:25:06',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            32 =>
            array(
                'id' => 46,
                'name' => 'SAMSOF PLAST',
                'email' => 'samsofplastbejaia@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$nTq6oc6qHZJoD8NQPudbCO3iCZUkvoC6OLw6yXpI2D4vtcuLWfkYm',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-26 10:04:59',
                'updated_at' => '2025-06-11 10:08:49',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            33 =>
            array(
                'id' => 48,
                'name' => 'EURL Porte Koudri',
                'email' => 'sarlkoudrimetal@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$QIFOV5hsGmb8/Pm52UkVMOUZeUsjqHO8hgmpT3gSndq1aWYMh3zEO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-26 13:06:58',
                'updated_at' => '2025-05-26 13:06:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            34 =>
            array(
                'id' => 49,
                'name' => 'Alim Zak',
                'email' => 'alimzakfrontekalgerie@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$osDvrfU41LdWVPncfArxcuM8YrsP/1ykqWEd55Z9Ahx14L3520X.O',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-05-28 09:40:33',
                'updated_at' => '2025-05-28 09:40:33',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            35 =>
            array(
                'id' => 50,
                'name' => 'LEADER ALUMINIUM',
                'email' => 'servicecomunication21@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$0JivRYw2/gV9kZpJwA.KGOGH.Sb6vP.oqVK/g3K8TJJLH9AouokM6',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-01 10:33:58',
                'updated_at' => '2025-06-03 14:55:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            36 =>
            array(
                'id' => 51,
                'name' => 'AZEDPLAST',
                'email' => 'Azedplast@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$KD.rJ9e8Hn0iXtIQhyqllew.qn18cuPb3g3YUQgLei/8Wf12h7A5m',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-01 10:46:44',
                'updated_at' => '2025-06-16 12:55:25',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            37 =>
            array(
                'id' => 53,
                'name' => 'Hasnaoui Profile Systems  HPS',
                'email' => 'berkanesalima.sb@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ptTxziHWK5rZqSV7IuvaR.Sp9z3Igg946TitgEe05CoEsZub96U8S',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-02 12:20:06',
                'updated_at' => '2025-06-17 13:46:40',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            38 =>
            array(
                'id' => 54,
                'name' => 'SARL ADN PROFILE',
                'email' => 'Contact@adnprofile.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Hc0exGYY06FAg6Pi5NRT0.CH78jwe2cAfu4Csn599Mfuw5vuXleQa',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-02 12:23:43',
                'updated_at' => '2025-06-17 08:30:05',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            39 =>
            array(
                'id' => 55,
                'name' => 'SARL IMP EXP FRERES OURAHMOUNE',
                'email' => 'djalil@groupe-ourahmoune.com',
                'verified_at' => NULL,
                'password' => '$2y$12$g7VEWWGIfLlSRCdpGVP9Oe1FFCrOgVkMphx5BGAAjuM9HuKxUAQ9q',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-02 12:26:13',
                'updated_at' => '2025-06-15 10:48:27',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            40 =>
            array(
                'id' => 56,
                'name' => 'SABA GLASS ',
                'email' => 'sabaglass.18@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$3z1MmPz2WFQPiw9f8Tf0PO9oc3LvMgJGWXhI767.MDEeYkxNcvZhy',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-02 12:29:07',
                'updated_at' => '2025-06-02 12:29:07',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            41 =>
            array(
                'id' => 57,
                'name' => 'SARL TIBON INDUSTRIE',
                'email' => 'amirakacem93@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$PwsZH.sNx7CO4dDbsJOJ.eAcR4b5/6d29iLrn52UgvUuTWHPvluu6',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-02 12:30:54',
                'updated_at' => '2025-06-02 12:30:54',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            42 =>
            array(
                'id' => 58,
                'name' => 'FUNDERMAX',
                'email' => 'sana.kharchi@alna-engineering.com',
                'verified_at' => NULL,
                'password' => '$2y$12$5xJ5NEvqL50/v8L6o7JRz.Mq/hRv31IXf8XpymMHol6zXss202UpW',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-03 08:24:21',
                'updated_at' => '2025-06-03 08:24:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            43 =>
            array(
                'id' => 60,
                'name' => 'NAWAFID PORTES & FENETRES PVC',
                'email' => 'amira.abedazzi@groupe-chiali.com',
                'verified_at' => NULL,
                'password' => '$2y$12$QN3dxiNEAP4a7sqOCmOzK.81vSTXHYSM9jvg0cZm0IaeYhVZVLUZW',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-19 09:52:52',
                'updated_at' => '2025-06-19 09:52:52',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            44 =>
            array(
                'id' => 61,
                'name' => 'GK PLAST ',
                'email' => 'gk_plast@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$N5ltHUc1DeLsDH/m3BMk5ey0PeGBSiv/FdjaeZL0zhi1LN19/uLji',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-22 14:19:40',
                'updated_at' => '2025-07-13 16:46:39',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            45 =>
            array(
                'id' => 62,
                'name' => 'RZ GLASS',
                'email' => 'Inoxal.contact@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$eapq.tl2ksGcKG4awelyge4dH6ijnU4SeVSQKryYU/NnMbXR7TtaO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-06-29 15:25:45',
                'updated_at' => '2025-06-29 15:25:45',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            46 =>
            array(
                'id' => 64,
                'name' => 'CBE',
                'email' => 'contact@cuisinebainexpo.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Ofrgu0YgrrljlgYETNi7Ye0nWOzKZCzaz9opc8gG7xA7wOUmehpoC',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 08:59:01',
                'updated_at' => '2025-07-01 09:16:22',
                'deleted_at' => '2025-07-01 09:16:22',
                'new_email' => NULL,
            ),
            47 =>
            array(
                'id' => 65,
                'name' => 'SARL ALL MAT ',
                'email' => 'allmat.office@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$wlQZjD.6h16xV/4Nv/v5z.4PE/j5BhiWLVOqblilqO8bI9xPVE2RO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 09:20:17',
                'updated_at' => '2025-07-01 10:17:06',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            48 =>
            array(
                'id' => 66,
                'name' => 'NATURA WOOD DESIGN ',
                'email' => 'naturawooddesign.18@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$tA1YCMEUkVjRQp9TilZ6k.ZeHHXGLWNIBTIlPYYLWaCOo.hVCWWVG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 09:38:30',
                'updated_at' => '2025-07-03 07:31:46',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            49 =>
            array(
                'id' => 67,
                'name' => 'SARL ATET DESIGN ',
                'email' => 'sarlatetdesign@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$CqovHnkX9O3HRHp50C8qsOzU.c.nVNNWCVvUQHII8.doNKrGdCAGK',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 09:41:40',
                'updated_at' => '2025-07-01 09:41:40',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            50 =>
            array(
                'id' => 68,
                'name' => 'HARIZ EL MAHDI',
                'email' => 'yagoubmou168@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$mhU3gZiR/cKU7r7qPnosfeDbVozjF61S70MkzAlrTYh1Q0CQhqT.S',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 09:46:26',
                'updated_at' => '2025-07-01 09:46:26',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            51 =>
            array(
                'id' => 69,
                'name' => 'EURL SIBEIFU INDUSTRIAL CO',
                'email' => 'ryma35010ryma@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$zSeW.kfGScjyUs2WNtTBh.ErUjDIUIMfPmzuRHimHrlAvnEDlVqh6',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 10:09:14',
                'updated_at' => '2025-07-01 10:09:14',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            52 =>
            array(
                'id' => 70,
                'name' => 'SARL ALUCOSTAR PLUS ',
                'email' => 's.rachid@alucostar.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$BRUgK3mJvOv4QLT2VBPOmuoXOIYGZH6Tfwn8Znn9b1VngYjsM7dWO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 12:32:13',
                'updated_at' => '2025-07-01 12:32:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            53 =>
            array(
                'id' => 71,
                'name' => 'EURL AB BOISSONS (JATIVA CERAM)',
                'email' => 'jativaceram@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$IyykqmdLMPmUzsB.TWgkCOT8yqvA80yGgnne9Zw4O8z/JI8b.CVH.',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 12:40:11',
                'updated_at' => '2025-07-01 12:40:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            54 =>
            array(
                'id' => 72,
                'name' => 'Panaf Makina Sanayi İthalat İhracat ve Ticaret Limited Şirketi',
                'email' => 'ali@panaf.com.tr',
                'verified_at' => NULL,
                'password' => '$2y$12$jQcpetCxRu9U9BOknN82neaaSVErTHyaRd6ESSQCEsYVuynIC8WCG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 12:45:40',
                'updated_at' => '2025-07-03 13:07:18',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            55 =>
            array(
                'id' => 73,
                'name' => 'MIRALUXE ATELIER DE FABRICATION DES PRODUITS DE DECORATION',
                'email' => 'cikoucorp@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$4bPpXnUyTDI7OV6EHsvHN.AsenBhwpfEC1Z4ZfliiXblB5gRwKZGO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 13:08:31',
                'updated_at' => '2025-07-01 13:08:31',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            56 =>
            array(
                'id' => 74,
                'name' => 'SARL RA REHAMENA',
                'email' => 'sarlrehamena@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$dKqmvU1azBhCvUGW7qzfY.qa8zNpoOOwkBtS4sBapl.cLwzdhjYUq',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 13:20:00',
                'updated_at' => '2025-07-01 13:20:00',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            57 =>
            array(
                'id' => 75,
                'name' => 'SARL DAXI ',
                'email' => 'sarldaxi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$t2Hu6iepKu9DRGUg9evizeP.Gu4CKpJqnXX6pu0uN/d79UvJpYPI6',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-01 13:58:07',
                'updated_at' => '2025-07-01 13:58:07',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            58 =>
            array(
                'id' => 76,
                'name' => 'HESTIA ',
                'email' => 'djameloughou@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$7xO1XGyLu9sO66Jhtimf1uPGm/vhZRyj14ggE/DrddPqFn1oeX5B.',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-03 15:05:02',
                'updated_at' => '2025-07-03 15:05:02',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            59 =>
            array(
                'id' => 77,
                'name' => 'POLYPROFILE',
                'email' => 'polyprofile@yahoo.com',
                'verified_at' => NULL,
                'password' => '$2y$12$DWmXMHd6n5b.Y8O5pC32lueH9XGopJzPo9xqgC/QzVyZ0qEOEnqmi',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-09 08:54:44',
                'updated_at' => '2025-07-09 08:54:44',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            60 =>
            array(
                'id' => 78,
                'name' => 'Klaes',
                'email' => 'Anouimehidi@klaes.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Sc4WLfsRmdVwCFTktuhKHubXDV1INOY0yUlsGJ5sRxrBM7PSSA5rG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-09 14:07:43',
                'updated_at' => '2025-07-09 14:07:43',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            61 =>
            array(
                'id' => 79,
                'name' => 'NeoBox ',
                'email' => 'caissontunnel@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$iuO81rvP66.xlFObGTU8cuQfPp2iwoCw4gEjb5zR6c.sGlJyRZmxq',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-15 12:17:58',
                'updated_at' => '2025-07-15 12:17:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            62 =>
            array(
                'id' => 80,
                'name' => 'HEDCOO',
                'email' => 'boulabyaranis@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$8cfeerL6oMk8QuVUpA1dLum1IOSQ8rsHMnKB7DsZRgBVKN.WUv3na',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-17 16:40:21',
                'updated_at' => '2025-07-17 16:40:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            63 =>
            array(
                'id' => 81,
                'name' => 'SOLUTION MODERNE ALUMINIUM ',
                'email' => 'Reda.bensari05@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Gii/ZL2tX5EacQNQO4dA6OKjJZ6RlUMd6xfXRDVZSwDaMbNgrgSzq',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-20 17:07:10',
                'updated_at' => '2025-07-20 17:07:10',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            64 =>
            array(
                'id' => 82,
                'name' => 'SARL Briquetterie EL Afaq',
                'email' => 'info@bourasgroup.com',
                'verified_at' => NULL,
                'password' => '$2y$12$V6zV5tepedfWDmQYPd40SuxBkHB39tWpW6IFBl.1pJXYwTajQ.5jS',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-22 09:44:11',
                'updated_at' => '2025-07-22 09:44:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            65 =>
            array(
                'id' => 83,
                'name' => 'ONYX  SOLID SURFACE DESIGN & SOLUTIONS',
                'email' => 'Onyxsolidsurface1@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$gJ/dcX0/2ijRb4V.hiibGOby1guLUMyx11OwGVk7e.z1KaG9vUqJG',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-22 09:51:32',
                'updated_at' => '2025-07-22 09:51:32',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            66 =>
            array(
                'id' => 84,
                'name' => 'Life Door',
                'email' => 'sarllifedoor@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$oNv2wnFK9irxAyHeTlnGhe0pdJYS.vNFp2Gp44.cswvykH1QMnXzO',
                'remember_token' => NULL,
                'currency' => 'DZD',
                'created_at' => '2025-07-23 14:38:10',
                'updated_at' => '2025-07-23 14:38:10',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
        ));
    }
}
