<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BACKUPBadgesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('badges')->delete();
        
        \DB::table('badges')->insert(array (
            0 => 
            array (
                'id' => 8,
                'code' => 'EXH-1-40-6853e8098c05a',
                'name' => 'LYNDA ABERKANE',
                'email' => 'samsofplastbejaia@gmail.com',
                'position' => 'Premier Responsable',
                'company' => 'SAMSOF PLAST Sarl',
                'visitor_submission_id' => NULL,
                'exhibitor_submission_id' => 40,
                'created_at' => '2025-06-19 10:35:53',
                'updated_at' => '2025-06-19 10:35:53',
            ),
            1 => 
            array (
                'id' => 9,
                'code' => 'EXH-1-40-6853e83a0d6d6',
                'name' => 'YOUCEF ABERKANE',
                'email' => 'samsofplastbejaia@gmail.com',
                'position' => 'COMMERCIAL',
                'company' => 'SAMSOF PLAST Sarl',
                'visitor_submission_id' => NULL,
                'exhibitor_submission_id' => 40,
                'created_at' => '2025-06-19 10:36:42',
                'updated_at' => '2025-06-19 10:36:42',
            ),
            2 => 
            array (
                'id' => 10,
                'code' => 'EXH-1-40-6853e8a1b71dc',
                'name' => 'KOUSSEILA SABAA',
                'email' => 'samsofplastbejaia@gmail.com',
                'position' => 'Technico-Commercial',
                'company' => 'SAMSOF PLAST Sarl',
                'visitor_submission_id' => NULL,
                'exhibitor_submission_id' => 40,
                'created_at' => '2025-06-19 10:38:25',
                'updated_at' => '2025-06-19 10:38:25',
            ),
            3 => 
            array (
                'id' => 11,
                'code' => 'EXH-1-40-6853e8a23dad1',
                'name' => 'BAYA OUAMRANE',
                'email' => 'samsofplastbejaia@gmail.com',
                'position' => 'Chargé des ventes',
                'company' => 'SAMSOF PLAST Sarl',
                'visitor_submission_id' => NULL,
                'exhibitor_submission_id' => 40,
                'created_at' => '2025-06-19 10:38:26',
                'updated_at' => '2025-06-19 10:38:26',
            ),
            4 => 
            array (
                'id' => 12,
                'code' => '48b4e9b0-e5d9-432a-a1d6-6880e9cd40c0',
                'name' => 'test',
                'email' => 'test@mail.com',
                'position' => NULL,
                'company' => NULL,
                'visitor_submission_id' => 8,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-06 11:15:01',
                'updated_at' => '2025-07-06 11:15:01',
            ),
            5 => 
            array (
                'id' => 13,
                'code' => '18e7b933-c56a-4e36-ad29-bcb02f2c268c',
                'name' => 'test',
                'email' => 'test@test.com',
                'position' => NULL,
                'company' => NULL,
                'visitor_submission_id' => 9,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-06 11:16:30',
                'updated_at' => '2025-07-06 11:16:30',
            ),
            6 => 
            array (
                'id' => 15,
                'code' => '065575c6-f073-42b4-9d46-e65a8b6c8a36',
                'name' => 'Abdennour ',
                'email' => 'abdennour.nouimehidi@gmail.com',
                'position' => NULL,
                'company' => NULL,
                'visitor_submission_id' => 11,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-09 10:41:25',
                'updated_at' => '2025-07-09 10:41:25',
            ),
            7 => 
            array (
                'id' => 17,
                'code' => '93f6a3e8-5565-45ac-8e94-c2916b23470a',
                'name' => 'rafik',
                'email' => 'honaba1807@mytaemin.com',
                'position' => 'Ingénieur',
                'company' => 'entreprise',
                'visitor_submission_id' => 13,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-11 17:34:42',
                'updated_at' => '2025-07-11 17:34:42',
            ),
            8 => 
            array (
                'id' => 20,
                'code' => '5c76ffff-723f-4e2d-a93b-15efcc14b1c3',
                'name' => 'ARAIBI MAHREZ',
                'email' => 'm.araibi@ffp-events.com',
                'position' => 'Chargé des Opérations',
                'company' => 'FFP EVENTS',
                'visitor_submission_id' => 14,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-13 11:04:09',
                'updated_at' => '2025-07-13 11:04:09',
            ),
            9 => 
            array (
                'id' => 21,
                'code' => '3a5f2d11-ff9d-4a1a-a4d1-edd6edeee0c8',
                'name' => 'test',
                'email' => 'test@email.com',
                'position' => 'Chargé du Développement',
                'company' => 'Entreprise',
                'visitor_submission_id' => 15,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-13 21:21:43',
                'updated_at' => '2025-07-13 21:21:43',
            ),
            10 => 
            array (
                'id' => 22,
                'code' => 'ae4ebf90-544d-40c4-989a-b5895e48a55b',
                'name' => 'Zerrouki Ibrahim',
                'email' => 'ibrahimzerrouki11@gmail.com',
                'position' => 'Directeur Commercial',
                'company' => 'SARL Genisurv ',
                'visitor_submission_id' => 16,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-14 15:45:31',
                'updated_at' => '2025-07-14 15:45:31',
            ),
            11 => 
            array (
                'id' => 23,
                'code' => '589e9fb8-f413-4363-92ed-d7f07faded39',
                'name' => 'Amrane abdelmalek ',
                'email' => 'adimcuisine@gmail.com',
                'position' => 'Gérant',
                'company' => 'ADIM cuisine / DLMeuble ',
                'visitor_submission_id' => 17,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-15 01:33:27',
                'updated_at' => '2025-07-15 01:33:27',
            ),
            12 => 
            array (
                'id' => 24,
                'code' => '000f2242-4919-4837-ba0b-4ab46e5ee363',
                'name' => 'Amine ben amraoui ',
                'email' => 'aminebenamraoui732@gmail.com',
                'position' => 'Entrepreneur',
                'company' => 'Amine alu pro pvc ',
                'visitor_submission_id' => 18,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-15 07:45:51',
                'updated_at' => '2025-07-15 07:45:51',
            ),
            13 => 
            array (
                'id' => 25,
                'code' => '75446f5d-cf1b-4fc0-b089-8aba168873a9',
                'name' => 'Ferhat',
                'email' => 'djalilferhat06@gmail.com',
                'position' => 'Étudiant',
                'company' => 'Ensta',
                'visitor_submission_id' => 19,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-15 13:37:34',
                'updated_at' => '2025-07-15 13:37:34',
            ),
            14 => 
            array (
                'id' => 26,
                'code' => '6361db97-67cc-44cd-b1bc-03cdd8b95230',
                'name' => 'Amira Talbi',
                'email' => 'dr.amiratalbi@gmail.com',
                'position' => 'Architecte',
                'company' => 'Amira Talbi',
                'visitor_submission_id' => 20,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-16 19:34:34',
                'updated_at' => '2025-07-16 19:34:34',
            ),
            15 => 
            array (
                'id' => 27,
                'code' => 'c94ea44e-23de-40d5-9e70-73bc078155e6',
                'name' => 'kaya sidali',
                'email' => 'kayafarouk2013@gmail.com',
                'position' => 'Directeur Technique',
                'company' => 'BEREP',
                'visitor_submission_id' => 21,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:23:43',
                'updated_at' => '2025-07-17 10:23:43',
            ),
            16 => 
            array (
                'id' => 28,
                'code' => '3b7f484f-0402-4a71-be3c-99ab49e4e50f',
                'name' => 'Teffahi salim',
                'email' => 'mussteffahi@gmail.com',
                'position' => 'Gérant',
                'company' => 'SARL TEFFAHI ',
                'visitor_submission_id' => 22,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:23:52',
                'updated_at' => '2025-07-17 10:23:52',
            ),
            17 => 
            array (
                'id' => 29,
                'code' => '56397792-f22b-48cc-8b0f-c7d65f842a01',
                'name' => 'Mezzelani',
                'email' => 'mezzelani.m@monticelli.it',
                'position' => 'Responsable Commercial',
                'company' => 'MONTICELLI',
                'visitor_submission_id' => 23,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:34:16',
                'updated_at' => '2025-07-17 10:34:16',
            ),
            18 => 
            array (
                'id' => 30,
                'code' => 'c84699e5-e766-49bd-bd12-7bbc06d6840c',
                'name' => 'Belhamri Line Yasmine',
                'email' => 'lynebelhamri@gmail.com',
                'position' => 'Fonctionnaire',
                'company' => 'Sarl Tech International ',
                'visitor_submission_id' => 24,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:44:56',
                'updated_at' => '2025-07-17 10:44:56',
            ),
            19 => 
            array (
                'id' => 31,
                'code' => '1152af52-e842-4b79-9be1-06bf10153dc8',
                'name' => 'ILEKTI hakim ',
                'email' => 'hakimilekti@gmail.com',
            'position' => 'Président Directeur Général (PDG)',
                'company' => 'SARL BISSIVAL ',
                'visitor_submission_id' => 25,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:47:29',
                'updated_at' => '2025-07-17 10:47:29',
            ),
            20 => 
            array (
                'id' => 32,
                'code' => '89034c3e-a14c-49de-a3df-451093b9d021',
                'name' => 'Chettir Aldjia',
                'email' => 'saravanraele@gmail.com',
                'position' => 'Fonctionnaire',
                'company' => 'Retraité ',
                'visitor_submission_id' => 26,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:49:24',
                'updated_at' => '2025-07-17 10:49:24',
            ),
            21 => 
            array (
                'id' => 33,
                'code' => '96a8d5c9-bd49-4251-8041-6b417ab5ff0e',
                'name' => 'MOHAMED merabia ',
                'email' => 'merabia.mohamed16@gmail.com',
                'position' => 'Fondateur',
                'company' => 'Merabia ',
                'visitor_submission_id' => 27,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 10:50:03',
                'updated_at' => '2025-07-17 10:50:03',
            ),
            22 => 
            array (
                'id' => 34,
                'code' => 'e7d5701c-8b0d-47ad-9bf1-a94c67e76b84',
                'name' => 'ARABI CHANEZ ',
                'email' => 'archi_ch@hotmail.fr',
                'position' => 'Architecte',
                'company' => 'Designer d\'intérieur  Auto-entrepreuneur ',
                'visitor_submission_id' => 28,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:11:18',
                'updated_at' => '2025-07-17 11:11:18',
            ),
            23 => 
            array (
                'id' => 35,
                'code' => '7917a5b7-ddc3-45ed-895b-c41cec327bbc',
                'name' => 'AOUCHER Ratiba',
                'email' => 'ratiba.aoucher@gmail.com',
                'position' => 'Fonctionnaire',
                'company' => 'SM-Fort',
                'visitor_submission_id' => 29,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:23:39',
                'updated_at' => '2025-07-17 11:23:39',
            ),
            24 => 
            array (
                'id' => 36,
                'code' => 'a612a697-54af-4d4b-8d11-4dd23f0fe6a9',
                'name' => 'AOUCHER Ratiba',
                'email' => 'ratiba.aoucher@gmail.com',
                'position' => 'Fonctionnaire',
                'company' => 'SM-FORT',
                'visitor_submission_id' => 30,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:26:16',
                'updated_at' => '2025-07-17 11:26:16',
            ),
            25 => 
            array (
                'id' => 37,
                'code' => '7e197b99-c421-47b7-bb60-2c75b6fff98e',
                'name' => 'Abdelhamid Boussaid',
                'email' => 'bsscrewnails@gmail.com',
                'position' => 'Fondateur',
                'company' => 'Boussaid Abdelhamid screw nails ',
                'visitor_submission_id' => 31,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:29:27',
                'updated_at' => '2025-07-17 11:29:27',
            ),
            26 => 
            array (
                'id' => 38,
                'code' => 'd46ed68b-c042-4683-8108-93c5dae9db29',
                'name' => 'Abdelhamid Boussaid',
                'email' => 'bsscrewnails@gmail.com',
                'position' => 'Fondateur',
                'company' => 'Boussaid Abdelhamid Screw Nails ',
                'visitor_submission_id' => 32,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:32:07',
                'updated_at' => '2025-07-17 11:32:07',
            ),
            27 => 
            array (
                'id' => 39,
                'code' => '8358344e-dc60-476e-8b6c-c15147bb282e',
                'name' => 'Mouhoun Abdelghani ',
                'email' => 'mouh.ghanou77@gmail',
                'position' => 'Gérant',
                'company' => 'Ghani gym ',
                'visitor_submission_id' => 33,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:35:45',
                'updated_at' => '2025-07-17 11:35:45',
            ),
            28 => 
            array (
                'id' => 40,
                'code' => '94bf7fd0-6616-47e0-85c1-1c2914d1b212',
                'name' => 'Medjaouri Hocine',
                'email' => 'kadrimiroiteriecomemrcial@gmail.com',
                'position' => 'Responsable Commercial',
                'company' => 'KADRI MIROITERIE',
                'visitor_submission_id' => 34,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 11:42:09',
                'updated_at' => '2025-07-17 11:42:09',
            ),
            29 => 
            array (
                'id' => 41,
                'code' => '834e3013-5e48-456d-ba7e-cc29734a4b68',
                'name' => 'Ouaar yassine ',
                'email' => 'ouaaryassine@gmail.com',
                'position' => 'Architecte',
                'company' => 'Bureau d\'études ',
                'visitor_submission_id' => 35,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 14:08:47',
                'updated_at' => '2025-07-17 14:08:47',
            ),
            30 => 
            array (
                'id' => 42,
                'code' => 'fd9bf963-2bc5-4e3b-bc54-6ae254a4846e',
                'name' => 'Yataghene',
                'email' => 'moun.yataghene@gmail.com',
                'position' => 'Architecte',
                'company' => 'Bureau d’etude',
                'visitor_submission_id' => 36,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 14:14:01',
                'updated_at' => '2025-07-17 14:14:01',
            ),
            31 => 
            array (
                'id' => 43,
                'code' => 'e37176aa-cee7-4bd2-a4ef-f3fa1392e3c1',
                'name' => 'Abderrahmane GHOZLANE',
                'email' => 'abder.ghozlane@gmail.com',
                'position' => 'Directeur Commercial',
                'company' => 'HUGE PUMP ',
                'visitor_submission_id' => 37,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 18:23:19',
                'updated_at' => '2025-07-17 18:23:19',
            ),
            32 => 
            array (
                'id' => 44,
                'code' => '592c8d79-e29a-468d-9e35-223e61e9d480',
                'name' => 'AIT ALI YAHIA Azeddine',
                'email' => 'azaitarchi@gmail.com',
                'position' => 'Architecte',
                'company' => 'BET AIT ALI YAHIA',
                'visitor_submission_id' => 38,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 18:26:26',
                'updated_at' => '2025-07-17 18:26:26',
            ),
            33 => 
            array (
                'id' => 45,
                'code' => 'dda06928-1fa9-4c8f-bd81-8d68518df5bf',
                'name' => 'AIT ALI YAHIA Azeddine',
                'email' => 'azaitarchi@gmail.com',
                'position' => 'Architecte',
                'company' => 'BET AIT ALI YAHIA',
                'visitor_submission_id' => 39,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 18:28:47',
                'updated_at' => '2025-07-17 18:28:47',
            ),
            34 => 
            array (
                'id' => 46,
                'code' => '0c629ae7-034d-447a-9cfd-4c23c84b51d6',
                'name' => 'SRIA AMAL',
                'email' => 'sriaamal@gmail.com',
                'position' => 'Commercial / Délégué',
                'company' => 'ACHGHAL',
                'visitor_submission_id' => 40,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 18:51:45',
                'updated_at' => '2025-07-17 18:51:45',
            ),
            35 => 
            array (
                'id' => 47,
                'code' => 'dba8e8b2-90af-4030-9847-8aea5560c134',
                'name' => 'SRIA AMAL',
                'email' => 'sriaamal@gmail.com',
                'position' => 'Commercial / Délégué',
                'company' => 'ACHGHAL',
                'visitor_submission_id' => 41,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 19:00:37',
                'updated_at' => '2025-07-17 19:00:37',
            ),
            36 => 
            array (
                'id' => 48,
                'code' => '14bf1784-90e3-474e-ae31-480242033bb9',
                'name' => 'Khaled Mubarak',
                'email' => 'khaled.mubarak@winkhaus.de',
                'position' => 'Directeur Commercial',
                'company' => 'Aug. Winkhaus SE',
                'visitor_submission_id' => 42,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-17 23:28:42',
                'updated_at' => '2025-07-17 23:28:42',
            ),
            37 => 
            array (
                'id' => 49,
                'code' => '1a3e5645-9a0c-4c4e-94cd-162bdacc4800',
                'name' => 'Zetchi Yanis ',
                'email' => 'yaniszetchi@hotmail.fr',
                'position' => 'Associé',
                'company' => 'ZETBIM',
                'visitor_submission_id' => 43,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 03:00:49',
                'updated_at' => '2025-07-18 03:00:49',
            ),
            38 => 
            array (
                'id' => 50,
                'code' => 'd20f5edb-9509-4518-9a2d-4aa5056822ff',
                'name' => 'Zetchi Yanis ',
                'email' => 'yaniszetchi@hotmail.fr',
                'position' => 'Associé',
                'company' => 'ZETBIM',
                'visitor_submission_id' => 44,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 03:03:07',
                'updated_at' => '2025-07-18 03:03:07',
            ),
            39 => 
            array (
                'id' => 51,
                'code' => '0f56fd46-2c0a-4569-a3e2-09145b27f850',
                'name' => 'ASLOUN NOURA',
                'email' => 'n.asloun@newhouseconcept.com',
            'position' => 'Directeur Général (DG)',
                'company' => ' ASLOUN  NEW HOUSE CONCEPT',
                'visitor_submission_id' => 45,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 10:54:59',
                'updated_at' => '2025-07-18 10:54:59',
            ),
            40 => 
            array (
                'id' => 52,
                'code' => '5d15dc27-7d12-42ba-9742-78c7685a895e',
                'name' => 'ASLOUN NOURA',
                'email' => 'n.asloun@newhouseconcept.com',
                'position' => 'Fondateur',
                'company' => 'ASLOUN NEW HOUSE CONCEPT',
                'visitor_submission_id' => 46,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 11:04:56',
                'updated_at' => '2025-07-18 11:04:56',
            ),
            41 => 
            array (
                'id' => 53,
                'code' => '8f14ffcc-d0cd-4f33-b037-b8deffbcc000',
                'name' => 'Yasmine LAIDANI',
                'email' => 'yasmine.laidani88@gmail.com',
                'position' => 'Entrepreneur',
                'company' => 'Dragon Pottery ',
                'visitor_submission_id' => 47,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 11:08:35',
                'updated_at' => '2025-07-18 11:08:35',
            ),
            42 => 
            array (
                'id' => 54,
                'code' => '31a18213-5e4f-4c18-84c6-fea017bbdd56',
                'name' => 'Yasmine LAIDANI',
                'email' => 'yasmine.laidani88@gmail.com',
                'position' => 'Entrepreneur',
                'company' => 'Dragon Pottery ',
                'visitor_submission_id' => 48,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 11:10:28',
                'updated_at' => '2025-07-18 11:10:28',
            ),
            43 => 
            array (
                'id' => 55,
                'code' => '67f200e6-3f53-4488-b67b-0e53881337bb',
                'name' => 'Mohamed ASLOUN',
                'email' => 'n.asloun@yahoo.com',
                'position' => 'Fondateur',
                'company' => 'ASLOUN NEW HOUSE CONCEPT',
                'visitor_submission_id' => 49,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 11:15:28',
                'updated_at' => '2025-07-18 11:15:28',
            ),
            44 => 
            array (
                'id' => 56,
                'code' => '3fbb7f27-2783-411a-8cca-726ae8304428',
                'name' => 'LACHACHI SALAHEDDINE',
                'email' => 'dprod@outlook.fr',
                'position' => 'Responsable Marketing et Communication',
                'company' => 'ASLOUN NEW HOUSE CONCEPT',
                'visitor_submission_id' => 50,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 11:30:08',
                'updated_at' => '2025-07-18 11:30:08',
            ),
            45 => 
            array (
                'id' => 57,
                'code' => '075e86ed-e6c4-497f-acdf-aab0ae55cee9',
                'name' => 'Sadaoui Rachid',
                'email' => 'rachid_sadaoui@yahoo.fr',
                'position' => 'Architecte',
                'company' => 'Patio',
                'visitor_submission_id' => 51,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 17:18:05',
                'updated_at' => '2025-07-18 17:18:05',
            ),
            46 => 
            array (
                'id' => 58,
                'code' => '2bb2ae3c-b7f5-464c-a146-8016fd51d115',
                'name' => 'TALEB Driss',
                'email' => 'd.taleb@iscotrans.it',
                'position' => 'Directeur des Opérations',
                'company' => 'ISCOTRANS ALG',
                'visitor_submission_id' => 52,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-18 17:43:19',
                'updated_at' => '2025-07-18 17:43:19',
            ),
            47 => 
            array (
                'id' => 59,
                'code' => '71cd0361-1e68-461a-8b35-50a44a6d5bef',
                'name' => 'Benarous Sihem ',
                'email' => 'sihembenarous1@gmail.com',
                'position' => 'Directeur Technique',
                'company' => 'Promotion immobilière ',
                'visitor_submission_id' => 53,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 06:36:16',
                'updated_at' => '2025-07-19 06:36:16',
            ),
            48 => 
            array (
                'id' => 60,
                'code' => 'e3716508-84fa-47ae-a6dd-3fe7573b61ce',
                'name' => 'Benarous Sihem ',
                'email' => 'sihembenarous1@gmail.com',
                'position' => 'Directeur Technique',
                'company' => 'Promotion immobilière ',
                'visitor_submission_id' => 54,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 06:38:15',
                'updated_at' => '2025-07-19 06:38:15',
            ),
            49 => 
            array (
                'id' => 61,
                'code' => '294adc28-31ac-4e06-a96f-ef5c03a25737',
                'name' => 'TAKELAIT MOHAMED SALAH ',
                'email' => 'takedecor.tg@gmail.com',
            'position' => 'Directeur Général (DG)',
                'company' => 'TAKE DECOR ',
                'visitor_submission_id' => 55,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 10:23:48',
                'updated_at' => '2025-07-19 10:23:48',
            ),
            50 => 
            array (
                'id' => 62,
                'code' => '1e23e6db-d0ed-4f7d-8172-b0ad38fa31b3',
                'name' => 'Boumendjel lakhdar',
                'email' => 'boumendjellakhdar@gmail.com',
                'position' => 'Architecte',
                'company' => 'Archi desk bl ',
                'visitor_submission_id' => 56,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 12:08:32',
                'updated_at' => '2025-07-19 12:08:32',
            ),
            51 => 
            array (
                'id' => 63,
                'code' => 'e34f8baa-d845-4d95-88bd-096e77f533cd',
                'name' => 'Nadir Lounaci',
                'email' => 'nadirlounaci@gmail.com',
                'position' => 'Gérant',
                'company' => 'ETS LOUNACI',
                'visitor_submission_id' => 57,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 16:38:29',
                'updated_at' => '2025-07-19 16:38:29',
            ),
            52 => 
            array (
                'id' => 64,
                'code' => '7a502730-5b91-484c-9826-e2cdc5c0788c',
                'name' => 'BENZINE Salim',
                'email' => 'benzine.salim@gmail.com',
                'position' => 'Architecte',
                'company' => 'BET ARCHIBENZ',
                'visitor_submission_id' => 58,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 21:33:21',
                'updated_at' => '2025-07-19 21:33:21',
            ),
            53 => 
            array (
                'id' => 65,
                'code' => '42c49f20-f879-4422-9802-8c012b3ecb89',
                'name' => 'BENZINE Salim',
                'email' => 'benzine.salim@gmail.com',
                'position' => 'Architecte',
                'company' => 'BET ARCHIBENZ',
                'visitor_submission_id' => 59,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-19 21:36:17',
                'updated_at' => '2025-07-19 21:36:17',
            ),
            54 => 
            array (
                'id' => 66,
                'code' => '63a9e75c-70ac-4cf0-bd1d-28ac5bbc981c',
                'name' => 'Chaibedra Sofiane ',
                'email' => 'chaisofiane18@gmail.com',
                'position' => 'Architecte',
                'company' => 'Art déco design ',
                'visitor_submission_id' => 60,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 00:03:54',
                'updated_at' => '2025-07-20 00:03:54',
            ),
            55 => 
            array (
                'id' => 67,
                'code' => '57e3f3f9-9913-46eb-84e7-4be81540710e',
                'name' => 'Wafa bennai ',
                'email' => 'wafaben_15@icloud.com',
                'position' => 'Fonctionnaire',
                'company' => 'Natixis ',
                'visitor_submission_id' => 61,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 09:49:11',
                'updated_at' => '2025-07-20 09:49:11',
            ),
            56 => 
            array (
                'id' => 68,
                'code' => 'a12ded68-30bf-4da0-9342-fd9bb53246ca',
                'name' => 'khellouf Djamel',
                'email' => 'khellouf_djamel@cscec.dz',
                'position' => 'Architecte',
                'company' => ' China State Construction Engineering Corporation Ltd.',
                'visitor_submission_id' => 62,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 11:20:05',
                'updated_at' => '2025-07-20 11:20:05',
            ),
            57 => 
            array (
                'id' => 69,
                'code' => 'c2a230b9-4230-4aba-a4b0-db53709cee11',
                'name' => 'Hana Bensaid ',
                'email' => 'hanaaelhayet34@gmail.com',
                'position' => 'Co-gérant',
                'company' => 'Brasseline house ',
                'visitor_submission_id' => 63,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 11:54:54',
                'updated_at' => '2025-07-20 11:54:54',
            ),
            58 => 
            array (
                'id' => 70,
                'code' => '33a8b3c8-6133-4be6-bcb7-655454897b70',
                'name' => 'Nacer MESSAOUDI',
                'email' => 'n.messaoudi@hotmail.com',
                'position' => 'Architecte',
                'company' => 'DAR EL IMAN',
                'visitor_submission_id' => 64,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 13:32:11',
                'updated_at' => '2025-07-20 13:32:11',
            ),
            59 => 
            array (
                'id' => 71,
                'code' => '79da1e36-724f-40f4-8350-6a8d1bbcbbdf',
                'name' => 'Nacer MESSAOUDI',
                'email' => 'n.messaoudi@hotmail.com',
                'position' => 'Architecte',
                'company' => 'DAR EL IMAN',
                'visitor_submission_id' => 65,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 13:38:06',
                'updated_at' => '2025-07-20 13:38:06',
            ),
            60 => 
            array (
                'id' => 72,
                'code' => '1f8ad7de-89fe-4ae3-997d-13a07ae6fe91',
                'name' => 'DORBANE Ahlem',
                'email' => 'dorbane.ahlem@gmail.com',
                'position' => 'Architecte',
                'company' => 'DAR EL IMAN',
                'visitor_submission_id' => 66,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 14:07:02',
                'updated_at' => '2025-07-20 14:07:02',
            ),
            61 => 
            array (
                'id' => 73,
                'code' => 'a403848a-7e8f-4ef3-b0f4-882b4ad2d04a',
                'name' => 'DORBANE Ahlem',
                'email' => 'dorbane.ahlem@gmail.com',
                'position' => 'Architecte',
                'company' => 'DAR EL IMAN',
                'visitor_submission_id' => 67,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 14:08:19',
                'updated_at' => '2025-07-20 14:08:19',
            ),
            62 => 
            array (
                'id' => 74,
                'code' => 'a56bddfc-41fa-45e6-bd87-4228eaf2967c',
                'name' => 'REGRADJ Meriem',
                'email' => 'm.regradj@dareliman.com',
                'position' => 'Ingénieur',
                'company' => 'DAR EL IMAN',
                'visitor_submission_id' => 68,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 14:12:08',
                'updated_at' => '2025-07-20 14:12:08',
            ),
            63 => 
            array (
                'id' => 75,
                'code' => '20a1457e-39ea-4eb8-b849-bd3b91cfc80a',
                'name' => 'REGRADJ Meriem',
                'email' => 'm.regradj@dareliman.com',
                'position' => 'Ingénieur',
                'company' => 'DAR EL IMAN',
                'visitor_submission_id' => 69,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 14:13:31',
                'updated_at' => '2025-07-20 14:13:31',
            ),
            64 => 
            array (
                'id' => 76,
                'code' => 'c2e9e81a-1df6-411e-aa34-922e3dfa7d20',
                'name' => 'Younes mechekak ',
                'email' => 'Younesmechekak1@gmail.com',
                'position' => 'Gérant',
                'company' => 'Menuiserie aluminium pvc',
                'visitor_submission_id' => 70,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 17:47:14',
                'updated_at' => '2025-07-20 17:47:14',
            ),
            65 => 
            array (
                'id' => 77,
                'code' => '193f0232-0b6c-4e2d-b61c-46a7c5a64bca',
                'name' => 'Khaled',
                'email' => 'contact@ffp-events.com',
                'position' => 'CEO',
                'company' => 'Winkhaus',
                'visitor_submission_id' => 71,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 21:12:49',
                'updated_at' => '2025-07-20 21:12:49',
            ),
            66 => 
            array (
                'id' => 78,
                'code' => 'feff937a-e3d2-43c2-b4bf-25b556764a90',
                'name' => 'Guellab',
                'email' => 'benfarida208@gmail.com',
                'position' => 'Consultant',
                'company' => 'Benbou',
                'visitor_submission_id' => 72,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-20 21:58:23',
                'updated_at' => '2025-07-20 21:58:23',
            ),
            67 => 
            array (
                'id' => 79,
                'code' => 'a1d6a963-861c-46a1-ba08-28341546c0fd',
                'name' => 'Madi amine ',
                'email' => 'amine3.3@hotmail.fr',
                'position' => 'Fondateur',
                'company' => 'Etb TCE Madi amine ',
                'visitor_submission_id' => 73,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 12:09:31',
                'updated_at' => '2025-07-21 12:09:31',
            ),
            68 => 
            array (
                'id' => 80,
                'code' => '6d40e956-b9a5-4ec4-acd5-5354453e941a',
                'name' => 'souhib djenaihi',
                'email' => 'alumondobiskra@gmail.com',
                'position' => 'CEO',
                'company' => 'Alum mondo',
                'visitor_submission_id' => 74,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 12:11:37',
                'updated_at' => '2025-07-21 12:11:37',
            ),
            69 => 
            array (
                'id' => 81,
                'code' => '7745fb92-36c0-4e15-b19c-6313cb405ded',
                'name' => 'toufik beche',
                'email' => 'toufalu@gmail.com',
                'position' => 'Gérant',
                'company' => 'Touf-alu hmd',
                'visitor_submission_id' => 75,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 14:03:48',
                'updated_at' => '2025-07-21 14:03:48',
            ),
            70 => 
            array (
                'id' => 82,
                'code' => 'b3b437d9-f161-4bae-a730-41b2598f33a1',
                'name' => 'BENNACEUR Salim',
                'email' => 'bennaceur_s@yahoo.fr',
                'position' => 'Consultant',
                'company' => 'Eiffage',
                'visitor_submission_id' => 76,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 14:22:39',
                'updated_at' => '2025-07-21 14:22:39',
            ),
            71 => 
            array (
                'id' => 83,
                'code' => 'be47db85-0ef7-432a-b2d6-4860394e6ea1',
                'name' => 'Hamichi Mohamed ',
                'email' => 'moh.hamichi@gmail.com',
                'position' => 'Responsable Commercial',
                'company' => 'SARL MEDICOMEDLINE',
                'visitor_submission_id' => 77,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 14:54:21',
                'updated_at' => '2025-07-21 14:54:21',
            ),
            72 => 
            array (
                'id' => 84,
                'code' => 'afffae89-e69a-4a2d-b3e5-f78336a3aa5a',
                'name' => 'Mohamed Amir Messaoudi',
                'email' => 'mohamedamir.messaoudi@gmail.com',
                'position' => 'Architecte',
                'company' => 'ENERECO',
                'visitor_submission_id' => 78,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 15:17:10',
                'updated_at' => '2025-07-21 15:17:10',
            ),
            73 => 
            array (
                'id' => 85,
                'code' => '53e74de5-e11c-4e2d-b670-9a0d3efbc94b',
                'name' => 'Mohamed Amir Messaoudi',
                'email' => 'mohamedamir.messaoudi@gmail.com',
                'position' => 'Architecte',
                'company' => 'ENERECO',
                'visitor_submission_id' => 79,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 15:20:07',
                'updated_at' => '2025-07-21 15:20:07',
            ),
            74 => 
            array (
                'id' => 86,
                'code' => '8d476c14-963e-4abc-9031-6f01a985fcd4',
                'name' => 'Hamichi Mohamed ',
                'email' => 'moh.hamichi@gmail.com',
                'position' => 'Responsable Commercial',
                'company' => 'SARL MEDICOMEDLINE ',
                'visitor_submission_id' => 80,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 15:27:04',
                'updated_at' => '2025-07-21 15:27:04',
            ),
            75 => 
            array (
                'id' => 87,
                'code' => 'e2b9e961-5ba2-41ad-8151-bac2b80ecfd9',
                'name' => 'Zakour ',
                'email' => 'm_zakour@yahoo.fr',
            'position' => 'Directeur Général (DG)',
                'company' => 'SARL MGB ZAKOUR FRERES ',
                'visitor_submission_id' => 81,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-21 20:09:29',
                'updated_at' => '2025-07-21 20:09:29',
            ),
            76 => 
            array (
                'id' => 88,
                'code' => 'e65d4881-304a-4b72-bfb1-5fdd3345e76a',
                'name' => 'MOHAMED SALAH BENCHERTIOUA ',
                'email' => 'souileh2@yahoo.fr',
                'position' => 'Responsable des Achats',
                'company' => 'MOHAMED SALAH BENCHERTIOUA ',
                'visitor_submission_id' => 82,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-22 08:50:34',
                'updated_at' => '2025-07-22 08:50:34',
            ),
            77 => 
            array (
                'id' => 89,
                'code' => '7c2aaff8-fed6-46b7-98e6-1fc37c036ad9',
                'name' => 'OURBIAH MOKRANE',
                'email' => 'mourbiah@cicalgeria.com.dz',
                'position' => 'Technico-commercial',
                'company' => 'CIC bureau de représentation',
                'visitor_submission_id' => 83,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-22 09:31:10',
                'updated_at' => '2025-07-22 09:31:10',
            ),
            78 => 
            array (
                'id' => 90,
                'code' => '9d13ad14-9c1b-4163-a551-d332b4bc6e77',
                'name' => 'CHEBILA Bilel',
                'email' => 'chebilabilel@gmail.com',
                'position' => 'Architecte',
                'company' => 'CSCEC',
                'visitor_submission_id' => 84,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-22 10:57:59',
                'updated_at' => '2025-07-22 10:57:59',
            ),
            79 => 
            array (
                'id' => 91,
                'code' => '2ef84956-4da2-4f22-9768-0d2bedf0a72f',
                'name' => 'Farouk debabeche ',
                'email' => 'faroukdebabeche@gmail.com',
                'position' => 'Commerçant',
                'company' => 'Farouk ',
                'visitor_submission_id' => 85,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-22 14:17:33',
                'updated_at' => '2025-07-22 14:17:33',
            ),
            80 => 
            array (
                'id' => 92,
                'code' => 'd5549170-d3c2-414f-b726-c9fd0fc75ca1',
                'name' => 'Mounira zerouali ',
                'email' => 'c.mounirazerouali22@gmail.com',
                'position' => 'Responsable Financier',
                'company' => 'Freelance EEP ',
                'visitor_submission_id' => 86,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-22 18:22:17',
                'updated_at' => '2025-07-22 18:22:17',
            ),
            81 => 
            array (
                'id' => 93,
                'code' => '5a6b0a46-4108-4681-986e-ebbdaa540da9',
                'name' => 'boumediene djallel',
                'email' => 'djallel@boumediene-engineering.com',
                'position' => 'Gérant',
                'company' => 'Boumediene Consultant Enginneering',
                'visitor_submission_id' => 87,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-23 10:21:31',
                'updated_at' => '2025-07-23 10:21:31',
            ),
            82 => 
            array (
                'id' => 94,
                'code' => '58297ccc-7d6d-424d-a1fc-6a416c82004c',
                'name' => 'Mameri hichem ',
                'email' => 'hi.mameri@gmail.com',
                'position' => 'Gérant',
                'company' => 'Sarl paradoxe immobilier ',
                'visitor_submission_id' => 88,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-23 14:31:23',
                'updated_at' => '2025-07-23 14:31:23',
            ),
            83 => 
            array (
                'id' => 95,
                'code' => '7ffede04-42ab-4c01-b99e-2be81927f682',
                'name' => 'belkacem Benyekhou',
                'email' => 'algamine23@hotmail.com',
                'position' => 'Gérant',
                'company' => 'amorial',
                'visitor_submission_id' => 89,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-23 23:01:44',
                'updated_at' => '2025-07-23 23:01:44',
            ),
            84 => 
            array (
                'id' => 96,
                'code' => '9ca8615c-7cb1-46d2-a2fb-c5bb4ba2c3bc',
                'name' => 'belkacem Benyekhou',
                'email' => 'algamine23@hotmail.com',
            'position' => 'Directeur Général (DG)',
                'company' => 'ETS Benyekhou',
                'visitor_submission_id' => 90,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-23 23:03:03',
                'updated_at' => '2025-07-23 23:03:03',
            ),
            85 => 
            array (
                'id' => 97,
                'code' => 'a5d9df03-d51a-40b4-a3f8-cd3340bc73d1',
                'name' => 'tesat',
                'email' => 'r_kouiderhacene@estin.dz',
                'position' => 'Directeur Technique',
                'company' => 'entre',
                'visitor_submission_id' => 91,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-26 15:19:28',
                'updated_at' => '2025-07-26 15:19:28',
            ),
            86 => 
            array (
                'id' => 98,
                'code' => '4700b456-cf5a-4eba-8f90-3e68c34d2bae',
                'name' => 'Hammadouche Houria',
                'email' => 'hammadouche.houria@gmail.com',
                'position' => 'CEO',
                'company' => 'Aluminium H &M',
                'visitor_submission_id' => 92,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-27 07:39:48',
                'updated_at' => '2025-07-27 07:39:48',
            ),
            87 => 
            array (
                'id' => 99,
                'code' => '691efa57-dac7-478b-80b3-7a18b3af2f85',
                'name' => 'Cheima Belhadad ',
                'email' => 'cheima.belhadad@yahoo.com',
                'position' => 'Architecte',
                'company' => 'SARL ALGÉRO-TURC',
                'visitor_submission_id' => 93,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-27 21:52:33',
                'updated_at' => '2025-07-27 21:52:33',
            ),
            88 => 
            array (
                'id' => 100,
                'code' => '7eb4bdcb-b507-4322-a67d-3fd601715ae7',
                'name' => 'nezai azzeddine',
                'email' => 'azzeddine.nezai@univ-saida.dz',
                'position' => 'Fonctionnaire',
                'company' => 'Université de Saida ',
                'visitor_submission_id' => 94,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 00:49:54',
                'updated_at' => '2025-07-28 00:49:54',
            ),
            89 => 
            array (
                'id' => 101,
                'code' => 'ae1daadd-6340-432f-9bd6-df531440fabc',
                'name' => 'Nezai Azzeddine ',
                'email' => 'nezai.azzeddine@gmail.com',
                'position' => 'Fonctionnaire',
                'company' => 'Université de Saida ',
                'visitor_submission_id' => 95,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 00:58:51',
                'updated_at' => '2025-07-28 00:58:51',
            ),
            90 => 
            array (
                'id' => 102,
                'code' => '1969a112-a72d-428c-afc6-d48f958f5b88',
                'name' => 'Akram Rouaman ',
                'email' => 'akramrm2003@gmail.com',
                'position' => 'Étudiant',
                'company' => 'École supérieure de statistiques et l\'économie appliquée ',
                'visitor_submission_id' => 96,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 02:34:34',
                'updated_at' => '2025-07-28 02:34:34',
            ),
            91 => 
            array (
                'id' => 103,
                'code' => 'f9f9fea2-3ad6-4ff6-92d8-7b9f5661cce9',
                'name' => 'Akram Rouaman ',
                'email' => 'akramrm2003@gmail.com',
                'position' => 'Étudiant',
                'company' => 'École nationale supérieure de statistique et d\'économie appliquée ',
                'visitor_submission_id' => 97,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 02:37:41',
                'updated_at' => '2025-07-28 02:37:41',
            ),
            92 => 
            array (
                'id' => 104,
                'code' => '7e2071a6-28b7-442c-8179-08a09a6f33ee',
                'name' => 'mahdi zehouani',
                'email' => 'zehouani.mehdi@gmail.com',
                'position' => 'Responsable Technique',
                'company' => 'Cosider promotion ',
                'visitor_submission_id' => 98,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 10:02:14',
                'updated_at' => '2025-07-28 10:02:14',
            ),
            93 => 
            array (
                'id' => 105,
                'code' => '65ff8fb8-1557-49e0-88be-503dd4313f06',
                'name' => 'Akretche Abdenour',
                'email' => 'abdenour.ak@gmail.com',
                'position' => 'Architecte',
                'company' => 'Cabinet d\'Architecte Abdenour Akretche',
                'visitor_submission_id' => 99,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 16:48:40',
                'updated_at' => '2025-07-28 16:48:40',
            ),
            94 => 
            array (
                'id' => 106,
                'code' => 'f2dc8192-db09-428f-bbe2-c198f083cfd2',
                'name' => 'Ahmed Khalil Bensaoudi',
                'email' => 'archi.bensaoudi@gmail.com',
                'position' => 'Gérant',
                'company' => 'BET GCET',
                'visitor_submission_id' => 100,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 18:04:00',
                'updated_at' => '2025-07-28 18:04:00',
            ),
            95 => 
            array (
                'id' => 107,
                'code' => '71d9e796-03a4-427d-aec3-3c466fb63c50',
                'name' => 'ali righi',
                'email' => 'righi.ali85@gmail.com',
                'position' => 'Menuisier',
                'company' => 'Chiali nawafid ',
                'visitor_submission_id' => 101,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 19:16:55',
                'updated_at' => '2025-07-28 19:16:55',
            ),
            96 => 
            array (
                'id' => 108,
                'code' => 'c43e2e35-6a45-4b73-acf8-14081feaa339',
                'name' => 'Mohamed Fayçal M\'hamdi',
                'email' => 'mhamdi.med.faycel@gmail.com',
                'position' => 'Commerçant',
                'company' => 'Benz-win ',
                'visitor_submission_id' => 102,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 23:47:36',
                'updated_at' => '2025-07-28 23:47:36',
            ),
            97 => 
            array (
                'id' => 109,
                'code' => '5d868667-e63d-4867-ad5b-2e0b6671e9ca',
                'name' => 'Mohamed Fayçal M\'hamdi',
                'email' => 'mhamdi.med.faycel@gmail.com',
                'position' => 'Commerçant',
                'company' => 'Benz-win',
                'visitor_submission_id' => 103,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-28 23:50:03',
                'updated_at' => '2025-07-28 23:50:03',
            ),
            98 => 
            array (
                'id' => 110,
                'code' => '73507632-5af3-4deb-94f0-fdd741d5ebcb',
                'name' => 'Dhia Eddine Ardjoune',
                'email' => 'Ardjoune_DhiaEddine@Engineer.com',
                'position' => 'CEO',
                'company' => 'B.E.T TTA ',
                'visitor_submission_id' => 104,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-29 02:09:53',
                'updated_at' => '2025-07-29 02:09:53',
            ),
            99 => 
            array (
                'id' => 111,
                'code' => 'ef44045e-f1a9-405d-ad20-8f7e899c819e',
                'name' => 'Atif Gherib',
                'email' => 'gheribatif@yahoo.fr',
                'position' => 'Menuisier',
                'company' => 'Gherib atef menuisier aluminium ',
                'visitor_submission_id' => 105,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-29 08:10:32',
                'updated_at' => '2025-07-29 08:10:32',
            ),
            100 => 
            array (
                'id' => 112,
                'code' => '2772b763-af2e-49e6-aefb-32e0cfb93098',
                'name' => 'talkarto',
                'email' => 'talkartohz@gmail.com',
                'position' => 'Menuisier',
                'company' => 'Menuiserie HM ',
                'visitor_submission_id' => 106,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-29 09:03:24',
                'updated_at' => '2025-07-29 09:03:24',
            ),
            101 => 
            array (
                'id' => 113,
                'code' => '174222f1-fee2-47e9-9884-6bc2002696d9',
                'name' => 'Hellal Merwan ',
                'email' => 'houriahh225@gmail.com',
                'position' => 'Entrepreneur',
                'company' => 'Menuiserie HM ',
                'visitor_submission_id' => 107,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-29 09:08:04',
                'updated_at' => '2025-07-29 09:08:04',
            ),
            102 => 
            array (
                'id' => 114,
                'code' => '3d71e44d-95af-4adf-a5a5-f64f078e1f44',
                'name' => 'Bet bonyan',
                'email' => 'bet.bonyan@gmail.com',
                'position' => 'Architecte',
                'company' => 'Bureau d\'étude Bonyan',
                'visitor_submission_id' => 108,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-29 11:56:16',
                'updated_at' => '2025-07-29 11:56:16',
            ),
            103 => 
            array (
                'id' => 115,
                'code' => 'bc47604a-b4be-4999-9e37-a4919f013206',
                'name' => 'Himeur soheyb ',
                'email' => 'Himeursoheyb@gmail.com',
                'position' => 'Architecte',
                'company' => 'Bet',
                'visitor_submission_id' => 109,
                'exhibitor_submission_id' => NULL,
                'created_at' => '2025-07-29 12:09:02',
                'updated_at' => '2025-07-29 12:09:02',
            ),
        ));
        
        
    }
}