<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BACKUPVisitorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('visitors')->delete();
        
        \DB::table('visitors')->insert(array (
            0 => 
            array (
                'id' => 8,
                'name' => 'groupe_bouras@yahoo.fr',
                'email' => 'groupe_bouras@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$TfQmFwok02sDxTJv3KTFXO04DrKSI5eZivaZKHBqtv.bdmiRWMes6',
                'remember_token' => NULL,
                'created_at' => '2025-06-09 09:23:15',
                'updated_at' => '2025-07-20 10:21:03',
                'deleted_at' => '2025-07-20 10:21:03',
                'new_email' => NULL,
            ),
            1 => 
            array (
                'id' => 10,
                'name' => 'Benaldi othmane',
                'email' => 'benaldiprince@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Rt3mHim8FIceVxoO//wG4u1oWzoJFbmCH1NT3LtwO/pIjKf01OdVu',
                'remember_token' => NULL,
                'created_at' => '2025-07-02 15:01:32',
                'updated_at' => '2025-07-20 10:21:17',
                'deleted_at' => '2025-07-20 10:21:17',
                'new_email' => NULL,
            ),
            2 => 
            array (
                'id' => 11,
                'name' => 'test',
                'email' => 'test@mail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$rCFQoYkA4OzdCG7naq77MOTS/ELLb8a3ynH/edlrkXCRt/3EbCOV6',
                'remember_token' => NULL,
                'created_at' => '2025-07-06 11:14:31',
                'updated_at' => '2025-07-20 10:20:53',
                'deleted_at' => '2025-07-20 10:20:53',
                'new_email' => NULL,
            ),
            3 => 
            array (
                'id' => 12,
                'name' => 'test',
                'email' => 'test@test.com',
                'verified_at' => NULL,
                'password' => '$2y$12$tLlqUgFbABqH0ImToCBw5.yheS9cmGmNjobsSDTll1Tqc1RmjNBLi',
                'remember_token' => NULL,
                'created_at' => '2025-07-06 11:16:01',
                'updated_at' => '2025-07-20 10:20:17',
                'deleted_at' => '2025-07-20 10:20:17',
                'new_email' => NULL,
            ),
            4 => 
            array (
                'id' => 13,
                'name' => 'Abdennour ',
                'email' => 'abdennour.nouimehidi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$sqHVDj6SLwjUn47m/CJmNe3NV4LZl6YU/FG/r0GBMyDXsvS8UomDq',
                'remember_token' => NULL,
                'created_at' => '2025-07-09 10:39:56',
                'updated_at' => '2025-07-20 10:20:06',
                'deleted_at' => '2025-07-20 10:20:06',
                'new_email' => NULL,
            ),
            5 => 
            array (
                'id' => 15,
                'name' => 'rafik',
                'email' => 'honaba1807@mytaemin.com',
                'verified_at' => NULL,
                'password' => '$2y$12$UgFTaD7Y8gPVd7LOC//dDes6dF8vov5C4Y34EUtOjKELLyLwWrG8q',
                'remember_token' => NULL,
                'created_at' => '2025-07-11 17:33:40',
                'updated_at' => '2025-07-11 17:33:40',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            6 => 
            array (
                'id' => 16,
                'name' => 'ARAIBI MAHREZ',
                'email' => 'm.araibi@ffp-events.com',
                'verified_at' => NULL,
                'password' => '$2y$12$U9oes7oToZFCESYXMcbdyOkJancI9HuHKBRMRq6XTKWSCKUsQX3Y.',
                'remember_token' => NULL,
                'created_at' => '2025-07-13 11:00:00',
                'updated_at' => '2025-07-20 10:19:49',
                'deleted_at' => '2025-07-20 10:19:49',
                'new_email' => NULL,
            ),
            7 => 
            array (
                'id' => 17,
                'name' => 'test',
                'email' => 'test@email.com',
                'verified_at' => NULL,
                'password' => '$2y$12$E5TNxX06rrYXuTImgBo6Du6yWpwOS3wg2eIpZM0X1Qc8WD4eARiMi',
                'remember_token' => NULL,
                'created_at' => '2025-07-13 21:20:37',
                'updated_at' => '2025-07-20 10:20:27',
                'deleted_at' => '2025-07-20 10:20:27',
                'new_email' => NULL,
            ),
            8 => 
            array (
                'id' => 18,
                'name' => 'Zerrouki Ibrahim',
                'email' => 'ibrahimzerrouki11@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$TRjFQLVOq8rvttN.8O8ThOXnp7kIQGNMyQG8AJBiCLKND3sln1jYy',
                'remember_token' => NULL,
                'created_at' => '2025-07-14 15:16:58',
                'updated_at' => '2025-07-14 15:16:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            9 => 
            array (
                'id' => 19,
                'name' => 'GOUMIRI Tahar ',
                'email' => 'pyramides.dz@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$979cibyit2cNvZPteQIvAujxGRfWNH.FTmmuScnUpKXI4OmIcVsoW',
                'remember_token' => NULL,
                'created_at' => '2025-07-14 15:53:21',
                'updated_at' => '2025-07-14 15:53:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            10 => 
            array (
                'id' => 20,
                'name' => 'Amrane abdelmalek ',
                'email' => 'adimcuisine@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$qZC8qPrW/BJ6tkURtZGlsuvr3bP9/qRTlRHaoO8/4SzOrsHkLqYOq',
                'remember_token' => NULL,
                'created_at' => '2025-07-15 01:20:16',
                'updated_at' => '2025-07-15 01:20:16',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            11 => 
            array (
                'id' => 21,
                'name' => 'Amine ben amraoui ',
                'email' => 'aminebenamraoui732@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$F76O.PS.gcpW68KcUzQTC.XjlbTHi6fu35WWOQLwvhLmmnHQm8bQ2',
                'remember_token' => NULL,
                'created_at' => '2025-07-15 07:39:51',
                'updated_at' => '2025-07-15 07:39:51',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            12 => 
            array (
                'id' => 22,
                'name' => 'Ferhat',
                'email' => 'djalilferhat06@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Vy75ccoyKcBD7zhdLAUNneE4F7sz58/zfpv8KURVn9ejwxnSAMbL2',
                'remember_token' => NULL,
                'created_at' => '2025-07-15 13:36:27',
                'updated_at' => '2025-07-15 13:36:27',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            13 => 
            array (
                'id' => 23,
                'name' => 'MEGHRAOUI Abdelhalim',
                'email' => 'halilmhr@gmail',
                'verified_at' => NULL,
                'password' => '$2y$12$LFrMAUJo7YEvll8VSkP0Hein8juZnEN.lRKN5et9nZ2wydM11B402',
                'remember_token' => NULL,
                'created_at' => '2025-07-15 15:42:31',
                'updated_at' => '2025-07-15 15:42:31',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            14 => 
            array (
                'id' => 24,
                'name' => 'ammari stores ',
                'email' => 'ammari_fouzi@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$Y7kCbSrRC7vAPAa3129UMeBnnwBv6qQAD8Sh8L0UOcrsdY.r25GvK',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 12:16:09',
                'updated_at' => '2025-07-16 12:16:09',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            15 => 
            array (
                'id' => 25,
                'name' => 'Ammam haroun',
                'email' => 'haroun781@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$g0WzAzWsBgp8mmvNYCZp2.KSJzXmGzoktGc6DILAi.yJp5PtmfXcq',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 12:24:13',
                'updated_at' => '2025-07-16 12:24:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            16 => 
            array (
                'id' => 26,
                'name' => 'Nabi  Abdelaziz ',
                'email' => 'nabiprofil@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Eo4.P4a3vKZO6.RWSdXzru0E7Bz1xQJbJ5oVD.1s2hBS.HjP2SfU2',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 13:56:10',
                'updated_at' => '2025-07-16 13:56:10',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            17 => 
            array (
                'id' => 27,
                'name' => 'Khalid saidi',
                'email' => 'gm.mccalgerie@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$qM6bZA6bnFjxI1ARiuR6I.ZY.JZPU8CE0oatgMw6uAE6kUFtnPG6y',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 14:17:01',
                'updated_at' => '2025-07-16 14:17:01',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            18 => 
            array (
                'id' => 28,
                'name' => 'Oulmou lachemi',
                'email' => 'oulmou.lachemi@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$9BBPymRSb7TKr4xWs8CD0.0P8wgXbcGbiSZ6pXhX3KUom.MMS9lR6',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 14:19:43',
                'updated_at' => '2025-07-16 14:19:43',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            19 => 
            array (
                'id' => 29,
                'name' => 'Heraoua ',
                'email' => 'heraouamustapha@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$3147Sop1z6Xg8H2zJ3o4FOD4Io/h5KmFK43.D5TF5L27QeXzdMtOe',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 15:52:01',
                'updated_at' => '2025-07-16 15:52:01',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            20 => 
            array (
                'id' => 30,
                'name' => 'حميد اوجانه رضوان',
                'email' => 'modarn.deco@glail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$AWzESlPKxhvCSRKesKzKyeQN0LThq5NKTDNBAkbcEndidbdubmS2q',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 16:21:04',
                'updated_at' => '2025-07-16 16:21:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            21 => 
            array (
                'id' => 31,
                'name' => 'Amira Talbi',
                'email' => 'dr.amiratalbi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$IZIyJCsSNtWHofC23J7xN.Ni5NHpSYb85yjjgsXY9virK53XeQG.e',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 19:32:23',
                'updated_at' => '2025-07-16 19:32:23',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            22 => 
            array (
                'id' => 32,
                'name' => 'Anis Belabbas',
                'email' => 'anis.belabbas@hotmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$QiP5ICZmIYPkZp8DSaNgE.fDysEK/ENBz4x2nikddHVN7a/dKkY5W',
                'remember_token' => NULL,
                'created_at' => '2025-07-16 23:33:21',
                'updated_at' => '2025-07-16 23:33:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            23 => 
            array (
                'id' => 33,
                'name' => 'ALIMAZIGHI Barken',
                'email' => 'age.calimazighi@cma-cgm.com',
                'verified_at' => NULL,
                'password' => '$2y$12$FyWMFqGG3Q1vY3VjMW85ceZMNeM/xpV6J7lSxcsawxuskrOxRPOOu',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:11:03',
                'updated_at' => '2025-07-17 10:11:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            24 => 
            array (
                'id' => 34,
                'name' => 'Benet FELIU',
                'email' => 'bfeliu@dsa.engineering',
                'verified_at' => NULL,
                'password' => '$2y$12$kjVZ1dM6rKKgp2P3qk9fJ.WdTBSpoU8DiNMpp/TwtfAaxanGiyzTi',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:13:03',
                'updated_at' => '2025-07-17 10:13:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            25 => 
            array (
                'id' => 35,
                'name' => 'Amine Aguenini',
                'email' => 'amine.archi1@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$mpJKfstN3SG53ZV30HLLged6qthn3wTDU3fsK7T6GYcMyd5C53n9u',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:16:20',
                'updated_at' => '2025-07-17 10:16:20',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            26 => 
            array (
                'id' => 36,
                'name' => 'kaya sidali',
                'email' => 'kayafarouk2013@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ARtbgaqg5FIDGP433tRIcObybd5wVCR.kQuMmUWJqY2ayXIfIxYPO',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:18:05',
                'updated_at' => '2025-07-17 10:18:05',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            27 => 
            array (
                'id' => 37,
                'name' => 'ROUABAH oussama',
                'email' => 'rouab.oussama@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$lpt12CBr1JUswnehrFhLCOzcRrPWrJd.LsJP.vYztYq/VmU9THuO6',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:19:46',
                'updated_at' => '2025-07-17 10:19:46',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            28 => 
            array (
                'id' => 38,
                'name' => 'Teffahi salim',
                'email' => 'mussteffahi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$.RmRIdou/C80GQCd6d7jwepKI03gINZIUhrgshO3vMi7HQOUqSlk2',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:19:48',
                'updated_at' => '2025-07-17 10:19:48',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            29 => 
            array (
                'id' => 39,
                'name' => 'ZAOUI SID CHIKH MOHAMMED',
                'email' => 'zaouipromotion@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$RR/PkGy19CKd/vjhF9qPB.SoqqjIW0Tnhgw3yPWrMJy6UYP7SvqGa',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:31:39',
                'updated_at' => '2025-07-17 10:31:39',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            30 => 
            array (
                'id' => 40,
                'name' => 'Mezzelani',
                'email' => 'mezzelani.m@monticelli.it',
                'verified_at' => NULL,
                'password' => '$2y$12$G5ugJehStob8UJHgqkn7PelQAfUTg..82WGMshbF.NBqgOJdIbWVO',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:32:03',
                'updated_at' => '2025-07-17 10:32:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            31 => 
            array (
                'id' => 41,
                'name' => 'Belhamri Line Yasmine',
                'email' => 'lynebelhamri@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Q397SrzbXiiXOoSbjwPd4eY0lvy9DnTCWPIbn1I20suNDhvhzBUhi',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:41:08',
                'updated_at' => '2025-07-17 10:41:08',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            32 => 
            array (
                'id' => 42,
                'name' => 'ILEKTI hakim ',
                'email' => 'hakimilekti@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$NzuAlApT.bTyla1Lx.ZhaOGiGnTTS5G7V6/Pekk43tTzIAz7J.A9a',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:44:28',
                'updated_at' => '2025-07-17 10:44:28',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            33 => 
            array (
                'id' => 43,
                'name' => 'Chettir Aldjia',
                'email' => 'saravanraele@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$OS6dDsqNg8iLR.3myo5wgecQlO1y3o6e.Y5EL8RexbPNiiehqll/i',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:46:40',
                'updated_at' => '2025-07-17 10:46:40',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            34 => 
            array (
                'id' => 44,
                'name' => 'MOHAMED merabia ',
                'email' => 'merabia.mohamed16@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Ix/BWWTlVqPpfzq1Z0oRi.Ua8yhA5WQ/XxLtBv4eDgbEwMo0sOGxO',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:47:53',
                'updated_at' => '2025-07-17 10:47:53',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            35 => 
            array (
                'id' => 45,
                'name' => 'Aloulou khaled ',
                'email' => 'Aloulou.khaled@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$aksN3c9oZWqso5y5RSq2Pe2P6vafmPm1cIzk/eLtRggo8.YH/2JGS',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:52:16',
                'updated_at' => '2025-07-17 10:52:16',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            36 => 
            array (
                'id' => 46,
                'name' => 'Benmamar djamal',
                'email' => 'benmamar_djamal@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$K4/6vWvdh59o3796EjGmduSAc1cGQAV7mcFAAjAZwKv1.FcW42w7G',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 10:55:31',
                'updated_at' => '2025-07-17 10:55:31',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            37 => 
            array (
                'id' => 47,
                'name' => 'BAKAIL LEA',
                'email' => 'lea.bakail@tyman.com',
                'verified_at' => NULL,
                'password' => '$2y$12$bvBau8hdh7BKbZ1StaAi6umiyTjC.sZRm1ogNRArsa9qjJxCwL0Za',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:04:27',
                'updated_at' => '2025-07-17 11:04:27',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            38 => 
            array (
                'id' => 48,
                'name' => 'ARABI CHANEZ ',
                'email' => 'archi_ch@hotmail.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$vbxzSEMURrWqHbjpNU8YqeQRCEtIEmvSrnUb.leUbMmUMzv2wifkW',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:07:11',
                'updated_at' => '2025-07-17 11:07:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            39 => 
            array (
                'id' => 49,
                'name' => 'AOUCHER Ratiba',
                'email' => 'ratiba.aoucher@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$TylDJqpuGK4YBm.3ldqGquzbhvz4b5KvVx1KHpXUXp0FEPUtwtQRq',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:17:43',
                'updated_at' => '2025-07-17 11:17:43',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            40 => 
            array (
                'id' => 50,
                'name' => 'Abdelhamid Boussaid',
                'email' => 'bsscrewnails@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$LmxHNDaK/wwfK8i2J9Uyh.BcWsB4YMnfGPeND4.jfieF2Lgjd2iEe',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:23:36',
                'updated_at' => '2025-07-17 11:23:36',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            41 => 
            array (
                'id' => 51,
                'name' => 'Ziada yassine ',
                'email' => 'pubplus@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$pTp56w3uSHnNXTvCfDlKIOyldKEzpV/iYyCzNtFsaHYBIscNHTKMu',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:24:24',
                'updated_at' => '2025-07-17 11:24:24',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            42 => 
            array (
                'id' => 52,
                'name' => 'Mouhoun Abdelghani ',
                'email' => 'mouh.ghanou77@gmail',
                'verified_at' => NULL,
                'password' => '$2y$12$k5.NJi3d0ZrU9mXw.03qcOXwB2KHOaFYARc1voO4VDhejb7B76ciC',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:30:29',
                'updated_at' => '2025-07-17 11:30:29',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            43 => 
            array (
                'id' => 53,
                'name' => 'Medjaouri Hocine',
                'email' => 'kadrimiroiteriecomemrcial@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$5sMlXUX13N1S.2ltp/XrE.toikQuGwX/wsENMne2SM2VXwRQKps2i',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:38:51',
                'updated_at' => '2025-07-17 11:38:51',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            44 => 
            array (
                'id' => 54,
                'name' => 'Derrouiche fahim ',
                'email' => 'f.derrouichebis@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$PWZXdqktX7yvlm0SLYlpw.H/U86.2Y79HxbYswAgfE4rLEO2qK.pO',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:48:11',
                'updated_at' => '2025-07-17 11:48:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            45 => 
            array (
                'id' => 55,
                'name' => 'Sahraoui Amine',
                'email' => 'amine.sahraoui@skyclean-algerie.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$x8zYaqvgreNJbGi3CBOhr.FMWi.bUjTEZru97AeVrJmMofYlUKSiC',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 11:55:04',
                'updated_at' => '2025-07-17 11:55:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            46 => 
            array (
                'id' => 56,
                'name' => 'guemari abderrezzak',
                'email' => 'guemarix@hotmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ASXDGcB4ZB16Fbac70Uj3.smsbLjPcLxassCl.nKv0DxqtInwa3yy',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 12:06:58',
                'updated_at' => '2025-07-17 12:06:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            47 => 
            array (
                'id' => 57,
                'name' => 'Aimane MAHDI',
                'email' => 'worldcenter2013@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$KIvWAa6xBTDSqyttxHdDq.6qZdZsVOimrPikKjD33jExcDjhsIpmC',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 12:10:48',
                'updated_at' => '2025-07-17 12:10:48',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            48 => 
            array (
                'id' => 58,
                'name' => 'KHETTOU ABDALLAH',
                'email' => 'abdallah.khettou@outlook.com',
                'verified_at' => NULL,
                'password' => '$2y$12$zpAwTwi0fHAQ1wHtvuzvyuijWS8i/O/vxauGSAVaeVKH1Bn3ObVW2',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 12:23:55',
                'updated_at' => '2025-07-17 12:23:55',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            49 => 
            array (
                'id' => 59,
                'name' => 'Azzoug A Halim ',
                'email' => 'halimazzoug4@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$TgXBfpdm5xStnqJ.QHcjHuAkoqg1awZN5a4eg2yvIbtWQFv1hTKW6',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 12:29:58',
                'updated_at' => '2025-07-17 12:29:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            50 => 
            array (
                'id' => 60,
                'name' => 'Amine OUZLIFI',
                'email' => 'ouzlifi_amine@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$x3HuXgoYErJgSnaXSy2S1eCKNsmHwBhB7QouLlc8fD11SYF/F920O',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 13:02:20',
                'updated_at' => '2025-07-17 13:02:20',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            51 => 
            array (
                'id' => 61,
                'name' => 'Mohamed Moulahoum',
                'email' => 'mohamed.moulahoum@yahoo.com',
                'verified_at' => NULL,
                'password' => '$2y$12$9.xbTwqXcUN.GRHGV5WyW.MVUDg9Vy4PnV6vm/I89yR3c2KFA84iq',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 13:30:18',
                'updated_at' => '2025-07-17 13:30:18',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            52 => 
            array (
                'id' => 62,
                'name' => 'Ouaar yassine ',
                'email' => 'ouaaryassine@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$0znbLTo6XVSsjS.AAVLHK.uIVFhekGLVzEe/3oiu93WrdqD/jnq06',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 14:05:11',
                'updated_at' => '2025-07-17 14:05:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            53 => 
            array (
                'id' => 63,
                'name' => 'Yataghene',
                'email' => 'moun.yataghene@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ucFdLaD1KTZmxYb0t9KDLuIUQVIhkj38XXu17uneW49f94YqYA9Xy',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 14:12:13',
                'updated_at' => '2025-07-17 14:12:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            54 => 
            array (
                'id' => 64,
                'name' => 'Rekia Merouane ',
                'email' => 'rekia.merouane@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$p9VYqLPHAZwrEHI0B33OQeffXLJWxaUpl3RhlIt3MGwPKQd1gJShy',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 14:49:41',
                'updated_at' => '2025-07-17 14:49:41',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            55 => 
            array (
                'id' => 65,
                'name' => 'Benzeghiba Rachida',
                'email' => 'benzeghiba34@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$n7utGDQhIQN2DyuqK22TO..wBj5lLWH6cL1AR5ud2BrNZunNMzOWC',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 14:56:14',
                'updated_at' => '2025-07-17 14:56:14',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            56 => 
            array (
                'id' => 66,
                'name' => 'BENNACEUR Salim',
                'email' => 'bennaceur_s@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$F6qX97sUxJMsWZrixiOipeTyCzgkZM5ulzvopTXApnF9LHsTXEqAa',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 15:30:19',
                'updated_at' => '2025-07-17 15:30:19',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            57 => 
            array (
                'id' => 67,
                'name' => 'Mostefaoui Sid Ali ',
                'email' => 'sidalimostefaoui31@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$cw6Tlg9YhoB/Qp80/f0w/u376oHzI2PqmFv4B9m2/QL1yoqfTPdum',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 17:30:20',
                'updated_at' => '2025-07-17 17:30:20',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            58 => 
            array (
                'id' => 68,
                'name' => 'Lagha Mustapha ',
                'email' => 'muslagha212@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$8/y8c3kOs/XkTP4UXULG6ur8jatYwi4Orl/wPC4gAA0TJlRBhr02.',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 17:58:27',
                'updated_at' => '2025-07-17 17:58:27',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            59 => 
            array (
                'id' => 69,
                'name' => 'AIT ALI YAHIA Azeddine',
                'email' => 'azaitarchi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$CGFp2y5xbMoLDjLAMR9ecOTYKWfmulw8nBq9kA5mznJjHC5jnjngK',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 18:00:58',
                'updated_at' => '2025-07-17 18:00:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            60 => 
            array (
                'id' => 70,
                'name' => 'Rebahi Amira ',
                'email' => 'rebahiamiramira@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$9BJibl0VE2dCy4NreMru1uZyaCSW/w4Luyx9emATui.7La0PrM2WC',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 18:11:14',
                'updated_at' => '2025-07-17 18:11:14',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            61 => 
            array (
                'id' => 71,
                'name' => 'Abderrahmane GHOZLANE',
                'email' => 'abder.ghozlane@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$EGSYer728a46tHgqKCfhOOMezthL3BToR.eJFM/wQlVmOD.pdAS5G',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 18:19:35',
                'updated_at' => '2025-07-17 18:19:35',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            62 => 
            array (
                'id' => 72,
                'name' => 'Rahmoune Ismail ',
                'email' => 'assist@altub-dz.com',
                'verified_at' => NULL,
                'password' => '$2y$12$u2oUli.fvGqmOhBnTxIKIug63Tj4UTYFCdyutvksXFJnX1QMhTiQS',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 18:35:09',
                'updated_at' => '2025-07-17 18:35:09',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            63 => 
            array (
                'id' => 73,
                'name' => 'SRIA AMAL',
                'email' => 'sriaamal@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ir9XvrD5B/5yE.vItXfXKuGILcOgZRq2nKhvz4j2v8pk62oJWTEuu',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 18:47:54',
                'updated_at' => '2025-07-17 18:47:54',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            64 => 
            array (
                'id' => 74,
                'name' => 'FARAH Chérif ',
                'email' => 'zit.cherif@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$.UZFpwQJo8oacvXeZXQBL.tJUBJswYiH3d5iLvYlfcQ6bmcxFORYq',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 19:43:20',
                'updated_at' => '2025-07-17 19:43:20',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            65 => 
            array (
                'id' => 75,
                'name' => 'ANTRI BOUZAR YOUCEF ',
                'email' => 'abyoucef60@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ZimHVHQuRIQNid07KojVvOuKMtdMtiOfqz1iSeXggGCrZ7ubGIoNm',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 21:14:23',
                'updated_at' => '2025-07-17 21:14:23',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            66 => 
            array (
                'id' => 76,
                'name' => 'Larbi daouadji ',
                'email' => 'bldaouadji@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$GusE6X35ZGY37tkfpz5qn./mPTckX566b7zMUWxhSL0.JYdRAaneq',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 22:00:28',
                'updated_at' => '2025-07-17 22:00:28',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            67 => 
            array (
                'id' => 77,
                'name' => 'LATRECHE Mourad ',
                'email' => 'latreche.m@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$lESUCcLnB9Z2Imrwh9Rc0eM3VKk0FX8C6fa1ZK/TlGVOeDPAcnC1O',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 22:01:59',
                'updated_at' => '2025-07-17 22:01:59',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            68 => 
            array (
                'id' => 78,
                'name' => 'gharssa toufik',
                'email' => 'gharssa_toufik@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$g/bJpyjBfOAg2dsqCXhzHu.A33O4hWJawvbxPVeS18NzZ4FKKZCAC',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 22:29:45',
                'updated_at' => '2025-07-17 22:29:45',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            69 => 
            array (
                'id' => 79,
                'name' => 'Khaled Mubarak',
                'email' => 'khaled.mubarak@winkhaus.de',
                'verified_at' => NULL,
                'password' => '$2y$12$nKHiiXJG1cl26q7v5PkH8.DCsevuOsnrXWygmRQFjc84c7Q4CyGyu',
                'remember_token' => NULL,
                'created_at' => '2025-07-17 23:21:59',
                'updated_at' => '2025-07-17 23:21:59',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            70 => 
            array (
                'id' => 80,
                'name' => 'Zetchi Yanis ',
                'email' => 'yaniszetchi@hotmail.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$TuwDZhJTTwfaKSgRIFqdHeOvU3nvuduvWUzUoQV35HRbv6alj5AKG',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 02:57:55',
                'updated_at' => '2025-07-18 02:57:55',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            71 => 
            array (
                'id' => 81,
                'name' => 'BAZINE Brahim ',
                'email' => 'b.bahi92@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$HSMnlBjfe8IoO73pOYLMTuaCAL58wpvhfk6lo4chi/2izQH23L7M6',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 05:35:11',
                'updated_at' => '2025-07-18 05:35:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            72 => 
            array (
                'id' => 82,
                'name' => 'ASLOUN NOURA',
                'email' => 'n.asloun@newhouseconcept.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Z5hmblrphGPoMyYHHQsDNuGNS2L94NGiUumxIJzLEgajRQWrxxLla',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 10:48:57',
                'updated_at' => '2025-07-18 10:48:57',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            73 => 
            array (
                'id' => 83,
                'name' => 'Yasmine LAIDANI',
                'email' => 'yasmine.laidani88@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ICvRSYxuQinGEqxAiMGXw.e7OPbMw1Fy6W1V356n9lQfebjtTIPhW',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 11:06:25',
                'updated_at' => '2025-07-18 11:06:25',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            74 => 
            array (
                'id' => 84,
                'name' => 'Mohamed ASLOUN',
                'email' => 'n.asloun@yahoo.com',
                'verified_at' => NULL,
                'password' => '$2y$12$7UQrC/1.pOQy7b/xwfVTT.oEflvI.rE0Tj5Bd9Jz3.8JGDNryKAV2',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 11:10:11',
                'updated_at' => '2025-07-18 11:10:11',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            75 => 
            array (
                'id' => 85,
                'name' => 'LACHACHI SALAHEDDINE',
                'email' => 'dprod@outlook.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$PXCUETO2VkUbMJcIxqRes.iaDANDxm6UDKBZSzb8u5QYQoKh4zyWG',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 11:25:35',
                'updated_at' => '2025-07-18 11:25:35',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            76 => 
            array (
                'id' => 86,
                'name' => 'Zoubir Aouag ',
                'email' => 'azmsaante@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Mj7C9jI7le7YDidvJ4feR.7veqEK2UDaMbiqvjkRffdwLSLNVxdqK',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 13:35:07',
                'updated_at' => '2025-07-18 13:35:07',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            77 => 
            array (
                'id' => 87,
                'name' => 'Djoweyda Adjili ',
                'email' => 'joodasinat@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$xp/gKc81tGmowjwDwci8xOYAIP41RH8O8KZyOmGPyKE49e8R1g7yi',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 15:15:13',
                'updated_at' => '2025-07-18 15:15:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            78 => 
            array (
                'id' => 88,
                'name' => 'kouadri mebarek',
                'email' => 'kouadriroutes@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$cg5gwipvFYt6gck7Nuid.OsfhbZzJp/YwXlAg2UPgaVYR3SHzuioe',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 16:43:13',
                'updated_at' => '2025-07-18 16:43:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            79 => 
            array (
                'id' => 89,
                'name' => 'Sadaoui Rachid',
                'email' => 'rachid_sadaoui@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$EHdkmFoQlub6HU7xdNO4muyIrEhOU4IMP9eBiL1li.0gOA0WMeaEG',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 16:59:28',
                'updated_at' => '2025-07-18 16:59:28',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            80 => 
            array (
                'id' => 90,
                'name' => 'TALEB Driss',
                'email' => 'd.taleb@iscotrans.it',
                'verified_at' => NULL,
                'password' => '$2y$12$527fpfOJMurwGONovdJo6e2v1e6NchfTzeWThBJZyehozDwh2uGWe',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 17:37:00',
                'updated_at' => '2025-07-18 17:37:00',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            81 => 
            array (
                'id' => 91,
                'name' => 'Karim Karim Mourad',
                'email' => 'kasoulimane@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$pGJUGY77/gFzD3tSMAqRVukBR7rxHAyeJT8ANyS9bOgrE2rQo1XiW',
                'remember_token' => NULL,
                'created_at' => '2025-07-18 19:50:23',
                'updated_at' => '2025-07-18 19:50:23',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            82 => 
            array (
                'id' => 92,
                'name' => 'Khelil Ali ',
                'email' => 'a.khelil@hydrodiver-dz.com',
                'verified_at' => NULL,
                'password' => '$2y$12$pI3EKpzHMwEtjK5tuREI5OzDeUx8US53JfJDqLZGN72qPd4efzefW',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 01:00:45',
                'updated_at' => '2025-07-19 01:00:45',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            83 => 
            array (
                'id' => 93,
                'name' => 'Bouguerouma Boualem',
                'email' => 'gerouteboualem@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$HgLNU2gsmKhv5V4ZrFfEC.hcMDMUnXLp009tNmhcPZG.tLHsx72ey',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 01:24:15',
                'updated_at' => '2025-07-19 01:24:15',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            84 => 
            array (
                'id' => 94,
                'name' => 'Benarous Sihem ',
                'email' => 'sihembenarous1@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$U2.jvNJi5XmnEZ5d374VoO0KAZ2UnqGjGS0KNj880Qfj79qH.0HBq',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 06:33:14',
                'updated_at' => '2025-07-19 06:33:14',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            85 => 
            array (
                'id' => 95,
                'name' => 'TAKELAIT MOHAMED SALAH ',
                'email' => 'takedecor.tg@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Hg15Wbgb.CbczWqcNlcppOby9K6KugxKTxNim8e5IZpQHFV.IMfhO',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 10:21:01',
                'updated_at' => '2025-07-19 10:21:01',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            86 => 
            array (
                'id' => 96,
                'name' => 'Boumendjel lakhdar',
                'email' => 'boumendjellakhdar@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$pkMtYNmlZUn0H14QCoN/Se.knXgk/6XkftiK5twznAgZXTj3KtoxW',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 12:07:30',
                'updated_at' => '2025-07-19 12:07:30',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            87 => 
            array (
                'id' => 97,
                'name' => 'Djamel bouhedjar',
                'email' => 'verre.dj@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$dbK5IqQDexseIO2xk/PRV.vmayKvYDUcgw/xBjgaO3G8JCYUG.M4O',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 14:57:22',
                'updated_at' => '2025-07-19 14:57:22',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            88 => 
            array (
                'id' => 98,
                'name' => 'Nadir Lounaci',
                'email' => 'nadirlounaci@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$zF7YCiclHr9aKH4.dDRqEOoXkjXDs0Akd3FJtZ2QH7KBLtn59Sl6.',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 16:34:16',
                'updated_at' => '2025-07-19 16:34:16',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            89 => 
            array (
                'id' => 99,
                'name' => 'Arbi Bouhana',
                'email' => 'bouhanaarbi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$NJbIdkDjy6A590lx9bMOA.78CuBMWwUp2Pc0AOVvKRo4T.WVXv8q.',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 20:14:45',
                'updated_at' => '2025-07-19 20:14:45',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            90 => 
            array (
                'id' => 100,
                'name' => 'BENZINE Salim',
                'email' => 'benzine.salim@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$fM04YXDzbZn6/dYcDlfJLODzpAdXkjMs/S8VlSPv5HVf1cXMsRdmy',
                'remember_token' => NULL,
                'created_at' => '2025-07-19 21:29:32',
                'updated_at' => '2025-07-19 21:29:32',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            91 => 
            array (
                'id' => 101,
                'name' => 'Chaibedra Sofiane ',
                'email' => 'chaisofiane18@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$z9cTmaOsCJLTfTCkrl8Pnutzvo72u02NuI7TZB6oozUPe31POvSoi',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 00:00:15',
                'updated_at' => '2025-07-20 00:00:15',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            92 => 
            array (
                'id' => 102,
                'name' => 'Wafa bennai ',
                'email' => 'wafaben_15@icloud.com',
                'verified_at' => NULL,
                'password' => '$2y$12$wP8c8ZPbJmNZIebjj./sbOE.6WY5iB3GSaXlVDFC7Fy4ixXA.QOcG',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 09:47:34',
                'updated_at' => '2025-07-20 09:47:34',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            93 => 
            array (
                'id' => 103,
                'name' => 'khellouf Djamel',
                'email' => 'khellouf_djamel@cscec.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$8w1T4yyy7H2PBMA9a1PBwOWhW9Txsysd8AfRzjweMpN4EiaMaRVla',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 11:16:20',
                'updated_at' => '2025-07-20 11:16:20',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            94 => 
            array (
                'id' => 104,
                'name' => 'Hana Bensaid ',
                'email' => 'hanaaelhayet34@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$3dbtuf5WYF2dvcBd/oYI1Oey2MAPOwV6STi1.k1AVNICWgL23jCqu',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 11:52:15',
                'updated_at' => '2025-07-20 11:52:15',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            95 => 
            array (
                'id' => 105,
                'name' => 'Touati mounira ',
                'email' => 'touati.lerari@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$NoUscVROVieKSSIkrR9zCOE9L8.NOO2cJ7rcgGKGXu5.z4zKt2I5q',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 12:05:12',
                'updated_at' => '2025-07-20 12:05:12',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            96 => 
            array (
                'id' => 106,
                'name' => 'MOHAMED MENTER',
                'email' => 'med.menter@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$dEHafKOgeA8xX0RCCHYe5OFzI77hOcnN/rBe.U8juCGUKvw/GtLL6',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 13:04:21',
                'updated_at' => '2025-07-20 13:04:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            97 => 
            array (
                'id' => 107,
                'name' => 'Nacer MESSAOUDI',
                'email' => 'n.messaoudi@dareliman.com',
                'verified_at' => NULL,
                'password' => '$2y$12$/cDdOjbkdl/nz5rFdxkTkeCiINNoqkYhKXuH0/3ocIj7SaKn8al5K',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 13:25:48',
                'updated_at' => '2025-07-20 13:40:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            98 => 
            array (
                'id' => 108,
                'name' => 'DORBANE Ahlem',
                'email' => 'dorbane.ahlem@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$0Or.MsvtdkdLuGwBJBEY2./vvmlYuNWQCWT8pzJrpQrSyeoq756T6',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 14:04:46',
                'updated_at' => '2025-07-20 14:04:46',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            99 => 
            array (
                'id' => 109,
                'name' => 'REGRADJ Meriem',
                'email' => 'm.regradj@dareliman.com',
                'verified_at' => NULL,
                'password' => '$2y$12$hTEcnRU.tHs5cVgDzcwdW.uYjlqf9EO6Qu..z7ZoMlq5fA7iSbyUe',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 14:09:50',
                'updated_at' => '2025-07-20 14:09:50',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            100 => 
            array (
                'id' => 110,
                'name' => 'Younes mechekak ',
                'email' => 'Younesmechekak1@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$LsHkJWOFVsoB0DZAHVBXTuP.XlZg2H5ENsenCJqrYdS5mBH4Yz3hO',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 17:43:13',
                'updated_at' => '2025-07-20 17:43:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            101 => 
            array (
                'id' => 111,
                'name' => 'Zakour ',
                'email' => 'm_zakour@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$EbEfRm4vGTJqDAe/2184rODsVSD6B4aTQuO97D6N4IdykY28uvQfm',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 18:47:48',
                'updated_at' => '2025-07-20 18:47:48',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            102 => 
            array (
                'id' => 112,
                'name' => 'filali fayçal',
                'email' => 'filali.archit@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$9pNlxIIGjSrK7SZdo67NRuCPbjiLu3oY7Yi7ONHAcdVaA76nODWMu',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 19:57:42',
                'updated_at' => '2025-07-20 19:57:42',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            103 => 
            array (
                'id' => 113,
                'name' => 'Khaled',
                'email' => 'contact@ffp-events.com',
                'verified_at' => NULL,
                'password' => '$2y$12$KvMb7ATLU8Uks9T5mV40U.66Ad7c5zFMtPdBT45ecR/ADDzqsbC/a',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 21:09:47',
                'updated_at' => '2025-07-20 21:09:47',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            104 => 
            array (
                'id' => 114,
                'name' => 'Guellab',
                'email' => 'benfarida208@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$5.DpFIkMND088rBNq8L4VuaQBmgsJ/iyd8MYoblE5hu83Jpf6ri/m',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 21:56:47',
                'updated_at' => '2025-07-20 21:56:47',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            105 => 
            array (
                'id' => 115,
                'name' => 'sadi el houcine ',
                'email' => 'el.houcine.sadi@outlook.com',
                'verified_at' => NULL,
                'password' => '$2y$12$kOWlNd5N7PKlAA.FA61B3.aeyMXsp93AeAPTLa/xu24jodOe.af52',
                'remember_token' => NULL,
                'created_at' => '2025-07-20 22:37:18',
                'updated_at' => '2025-07-20 22:37:18',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            106 => 
            array (
                'id' => 116,
                'name' => 'Madi amine ',
                'email' => 'amine3.3@hotmail.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$V7zr3cwcO2.kGb2LaWHttu4bxOZHGD6d3ZJMDMyKe1txIEcQ5XwTe',
                'remember_token' => NULL,
                'created_at' => '2025-07-21 12:03:18',
                'updated_at' => '2025-07-21 12:03:18',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            107 => 
            array (
                'id' => 117,
                'name' => 'souhib djenaihi',
                'email' => 'alumondobiskra@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Z2ezZ16G3JsVWpJGf/7GIe//EwL7J5vZ5rvCmwWeDpTpAb0TOeKU2',
                'remember_token' => NULL,
                'created_at' => '2025-07-21 12:09:38',
                'updated_at' => '2025-07-21 12:09:38',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            108 => 
            array (
                'id' => 118,
                'name' => 'toufik beche',
                'email' => 'toufalu@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$XCdJz0WWutiIy0KGooD9J.aRyuB7xDo5ZdGU9VmTidnJwReHpjHE2',
                'remember_token' => NULL,
                'created_at' => '2025-07-21 13:59:29',
                'updated_at' => '2025-07-21 13:59:29',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            109 => 
            array (
                'id' => 119,
                'name' => 'Hamichi Mohamed ',
                'email' => 'moh.hamichi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$VYjGSZUhErPjTQ4whiZR/ep.eV4pYyUFrZD9hkXtFPaZJ5ydSuu/y',
                'remember_token' => NULL,
                'created_at' => '2025-07-21 14:49:56',
                'updated_at' => '2025-07-21 14:49:56',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            110 => 
            array (
                'id' => 120,
                'name' => 'Mohamed Amir Messaoudi',
                'email' => 'mohamedamir.messaoudi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Tu/dSuOkmpRNKjDD1joSFeMCcptFh8NydIB/mUQl5vFgth/CiClY2',
                'remember_token' => NULL,
                'created_at' => '2025-07-21 15:09:03',
                'updated_at' => '2025-07-21 15:09:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            111 => 
            array (
                'id' => 121,
                'name' => 'MOHAMED SALAH BENCHERTIOUA ',
                'email' => 'souileh2@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$QeHZjNUcWUijErkAiJWtkurmScXJlz.2gClZ4VLwvtG8BkL0rFpMu',
                'remember_token' => NULL,
                'created_at' => '2025-07-22 08:45:54',
                'updated_at' => '2025-07-22 08:45:54',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            112 => 
            array (
                'id' => 122,
                'name' => 'OURBIAH MOKRANE',
                'email' => 'mourbiah@cicalgeria.com.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$RdgmlhYlTf.tGCdwncq.6esOBL3/hqadKPJtY2Q9ogoLBp0wqOIzq',
                'remember_token' => NULL,
                'created_at' => '2025-07-22 09:28:48',
                'updated_at' => '2025-07-22 09:28:48',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            113 => 
            array (
                'id' => 123,
                'name' => 'Nadia MEBARKI',
                'email' => 'nadiameb@hotmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$AoFq06oGgj5NyqL4Efo6Ae3FTyByerYjzzwMLcHYqqvZPevWUrfCW',
                'remember_token' => NULL,
                'created_at' => '2025-07-22 09:38:22',
                'updated_at' => '2025-07-22 09:38:22',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            114 => 
            array (
                'id' => 124,
                'name' => 'CHEBILA Bilel',
                'email' => 'chebilabilel@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$G0lxTKCDOLtT873Mmx6P7u9F2s1m1cxyi/O/vC40AMt9TqN6Jdz5C',
                'remember_token' => NULL,
                'created_at' => '2025-07-22 10:54:54',
                'updated_at' => '2025-07-22 10:54:54',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            115 => 
            array (
                'id' => 125,
                'name' => 'Farouk debabeche ',
                'email' => 'faroukdebabeche@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Dyd2A9hFjdtKQrlwXhTQuev7S.hwtqH/S26264c6LO1wTFHM954by',
                'remember_token' => NULL,
                'created_at' => '2025-07-22 14:10:22',
                'updated_at' => '2025-07-22 14:10:22',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            116 => 
            array (
                'id' => 126,
                'name' => 'Mounira zerouali ',
                'email' => 'c.mounirazerouali22@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$KQ0s5ahmSW6WQGG6tJEj0e2hDgUAQRTrrKARUL5YBlyytHOXOHe/y',
                'remember_token' => NULL,
                'created_at' => '2025-07-22 18:20:38',
                'updated_at' => '2025-07-22 18:20:38',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            117 => 
            array (
                'id' => 127,
                'name' => 'boumediene djallel',
                'email' => 'djallel@boumediene-engineering.com',
                'verified_at' => NULL,
                'password' => '$2y$12$O4x/aflVTgXCRoWb0eGaoOov3oJIg93gYl4NClVeCrEp5Sy1cOzIi',
                'remember_token' => NULL,
                'created_at' => '2025-07-23 10:04:49',
                'updated_at' => '2025-07-23 10:04:49',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            118 => 
            array (
                'id' => 128,
                'name' => 'Mameri hichem ',
                'email' => 'hi.mameri@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$It3uume2zcOLFJaMWISGo.ExwKrv0BCvDefWAvFqw.abDAZmz680q',
                'remember_token' => NULL,
                'created_at' => '2025-07-23 14:17:53',
                'updated_at' => '2025-07-23 14:17:53',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            119 => 
            array (
                'id' => 129,
                'name' => 'Hasni Samir',
                'email' => 'hasnisamir@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$MgU2m9w4aXyCH2vUgpkruO8l9Aw2uzxyDL24dOCh3fSDulovqsiLi',
                'remember_token' => NULL,
                'created_at' => '2025-07-23 17:07:58',
                'updated_at' => '2025-07-23 17:07:58',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            120 => 
            array (
                'id' => 130,
                'name' => 'belkacem Benyekhou',
                'email' => 'algamine23@hotmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$H5t62LpwMPLnbDTDcMOBg.QKBZYhdgT6CKQ8GbdgANOa57zaajhvW',
                'remember_token' => NULL,
                'created_at' => '2025-07-23 22:58:27',
                'updated_at' => '2025-07-23 22:58:27',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            121 => 
            array (
                'id' => 131,
                'name' => 'Boussa amar',
                'email' => 'saniplus35@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$.83Mr.HIfyrzU4h2D8Bn3OCdvwFPN3DU/g2CdrBgny9.PhYeFs7i2',
                'remember_token' => NULL,
                'created_at' => '2025-07-24 11:35:13',
                'updated_at' => '2025-07-24 11:35:13',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            122 => 
            array (
                'id' => 132,
                'name' => 'Khaled.Hadjkaddour@yahoo.fr',
                'email' => 'khaled.hadjkaddour@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$njNMu1yZVZoBXKE..lexX.fs6UrAc8A5WYExlxjoKJjOUOqZJ.mEO',
                'remember_token' => NULL,
                'created_at' => '2025-07-25 16:04:03',
                'updated_at' => '2025-07-25 16:04:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            123 => 
            array (
                'id' => 133,
                'name' => 'Laouari Omar',
                'email' => 'omarlaouari@globalsolutiontechnologie.com',
                'verified_at' => NULL,
                'password' => '$2y$12$6qIUxDFAgYPmk2h7RGH6e.Tyt30cwsPkI8j8P0KHfuWrfU9JHt/5C',
                'remember_token' => NULL,
                'created_at' => '2025-07-26 00:17:39',
                'updated_at' => '2025-07-26 00:17:39',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            124 => 
            array (
                'id' => 134,
                'name' => 'Manseur mohand Ouali billlel ',
                'email' => 'manseurbilel298@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$c7DohELjsh4OBxbO5B6PdOzN3CKbxQ0tgZMNgV16nH7x2qOtlk/Bq',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 00:35:35',
                'updated_at' => '2025-07-27 00:35:35',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            125 => 
            array (
                'id' => 135,
                'name' => 'Chafik',
                'email' => 'chefconfort47@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$acrpmwKwNBtlUbBwveKZCOsGeZ0mu0Et5kd.y/bzMTfzKMbwnd1fu',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 01:55:59',
                'updated_at' => '2025-07-27 01:55:59',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            126 => 
            array (
                'id' => 136,
                'name' => 'Hammadouche Houria',
                'email' => 'hammadouche.houria@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$sTAO6rEy2sfZGp/MUCWlOuafjtxPQNNq531xQmzzeSNXpatY.nMJO',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 07:36:54',
                'updated_at' => '2025-07-27 07:36:54',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            127 => 
            array (
                'id' => 137,
                'name' => 'Joud djwad',
                'email' => 'benzjoud02@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$ji1nThbQxXcO977/itfdEOMqyLflXSeo0wkTEveE8BbKKoC7qAOoS',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 11:20:06',
                'updated_at' => '2025-07-27 12:14:50',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            128 => 
            array (
                'id' => 138,
                'name' => 'KHALED ISSOLAH ',
                'email' => 'k.issolah@netstation.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$nT9wefFoEudCYGFyIQoyMOaUZGbCBblO3uqk3woPuLS/IEhYZGABS',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 15:46:12',
                'updated_at' => '2025-07-27 15:46:12',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            129 => 
            array (
                'id' => 139,
                'name' => 'Amin Terki',
                'email' => 'terkiamin60@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$r9UIVMLiqITYATzP7gMqO.ZXJryb2Cduxhx2hPt.Y0sg5sBl0QRVW',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 18:31:29',
                'updated_at' => '2025-07-27 18:31:29',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            130 => 
            array (
                'id' => 140,
                'name' => 'Cheima Belhadad ',
                'email' => 'cheima.belhadad@yahoo.com',
                'verified_at' => NULL,
                'password' => '$2y$12$rWF8paB1LV0bipw35r2uoeYPb9NlVcdaUUB4dLItHR6./GgexvO4y',
                'remember_token' => NULL,
                'created_at' => '2025-07-27 21:50:23',
                'updated_at' => '2025-07-27 21:50:23',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            131 => 
            array (
                'id' => 141,
                'name' => 'nezai azzeddine',
                'email' => 'azzeddine.nezai@univ-saida.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$jZOh6rUCGRZ9OaagsSC7PupdwXCgnJC./4mXDZSxsY1icH3goThiq',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 00:42:23',
                'updated_at' => '2025-07-28 00:42:23',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            132 => 
            array (
                'id' => 142,
                'name' => 'Nezai Azzeddine ',
                'email' => 'nezai.azzeddine@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$tWWKyc2/NCe4WXnVcW9hWuh7PbL1xLU86JL4nWfQl/ZoPvBCWU0xG',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 00:56:26',
                'updated_at' => '2025-07-28 00:56:26',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            133 => 
            array (
                'id' => 143,
                'name' => 'Akram Rouaman ',
                'email' => 'akramrm2003@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$k9B86gP.eLoRz.Yk8jvQbeTz34FRvjREqnPg1/2goWOOg1byiHWru',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 02:32:05',
                'updated_at' => '2025-07-28 02:32:05',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            134 => 
            array (
                'id' => 144,
                'name' => 'mahdi zehouani',
                'email' => 'zehouani.mehdi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$oLaDIm/Fu5.3isLg3GRn2.Jqmj4chNheY4F9xT1gMxSREuwDrVCVm',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 09:59:32',
                'updated_at' => '2025-07-28 09:59:32',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            135 => 
            array (
                'id' => 145,
                'name' => 'Djeghader Mohamed ',
                'email' => 'djeghadermohamed043@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$0tozk8G6qMX0zZBtLVwtPOs14AqoO.ivrw.5Z.t7a4kWWLUrr9qji',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 12:44:03',
                'updated_at' => '2025-07-28 12:44:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            136 => 
            array (
                'id' => 146,
                'name' => 'Agoudjil Mohamed',
                'email' => 'magoudjil@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$nqF7/Y6QnfGKWeD9657bHOr2myEBIkUV1JlIgrFuYkVai9e6h.Q4S',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 13:48:08',
                'updated_at' => '2025-07-28 13:48:08',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            137 => 
            array (
                'id' => 147,
                'name' => 'Akretche Abdenour',
                'email' => 'abdenour.ak@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$vVvEg4OFTqpT8LsjTX0XueAkBWo.LL78KrQhqsa48C8KKFI05kyla',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 16:45:53',
                'updated_at' => '2025-07-28 16:45:53',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            138 => 
            array (
                'id' => 148,
                'name' => 'Ahmed Khalil Bensaoudi',
                'email' => 'archi.bensaoudi@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Awq6NROYFKT7X/dwa6slAuN.iYdQj82pB72e9em2w6QemT2wRXpS2',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 18:02:38',
                'updated_at' => '2025-07-28 18:02:38',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            139 => 
            array (
                'id' => 149,
                'name' => 'ali righi',
                'email' => 'righi.ali85@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Kbh5fAbZFA9KNtIdKZ7FFu8ulJ3Q/F1zXgdtvHNd5AX4uenrmS2H2',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 19:09:36',
                'updated_at' => '2025-07-28 19:09:36',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            140 => 
            array (
                'id' => 150,
                'name' => 'Wahidamastour',
                'email' => 'wahidamastour157@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$5/qFZgRz7vYn2qsxJgc6We/SNpYoJnK9laCnywnklJpUNncaNILV2',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 19:15:03',
                'updated_at' => '2025-07-28 19:15:03',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            141 => 
            array (
                'id' => 151,
                'name' => 'DJERMANI Mohamed ',
                'email' => 'meddjermani@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$vWbbYOL58U9TpnNvmztDw.JiUSzWpBven18sXQs0FqarBcRslVOS.',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 20:03:30',
                'updated_at' => '2025-07-28 20:03:30',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            142 => 
            array (
                'id' => 152,
                'name' => 'Abbas Djoudi',
                'email' => 'djoudiabbas@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$QOYDeGW4CUilTD0m9aVMhu3CgUqZccwKnGwOpMnJ3e/W/mRjQvS7C',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 21:18:33',
                'updated_at' => '2025-07-28 21:18:33',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            143 => 
            array (
                'id' => 153,
                'name' => 'Belaid Tarek ',
                'email' => 'tbelaid8@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$EOb3cZVT1fczohSSTDyL/ObdJxfag3/TKVMN5OcWcn8b0jrvWDvW.',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 21:36:25',
                'updated_at' => '2025-07-28 21:36:25',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            144 => 
            array (
                'id' => 154,
                'name' => 'Mohamed Fayçal M\'hamdi',
                'email' => 'mhamdi.med.faycel@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$0iDjB29xFq79KAezyW5AgOd2Lq2.TO/zYmQTWPbsZxyJbz816AclK',
                'remember_token' => NULL,
                'created_at' => '2025-07-28 23:44:39',
                'updated_at' => '2025-07-28 23:44:39',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            145 => 
            array (
                'id' => 155,
                'name' => 'Toualeb rabah ',
                'email' => 'rabah.toualeb@infratele.dz',
                'verified_at' => NULL,
                'password' => '$2y$12$8hsvZhJIe7st95zZoeQWT.wGzKpqp1xsi0B1hnxEl3r7PTQZspCUW',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 01:40:18',
                'updated_at' => '2025-07-29 01:40:18',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            146 => 
            array (
                'id' => 156,
                'name' => 'Dhia Eddine Ardjoune',
                'email' => 'Ardjoune_DhiaEddine@Engineer.com',
                'verified_at' => NULL,
                'password' => '$2y$12$dH3vNEDUP6WtdR1taJ70BOQQqsBWZF52/5qq01TNCfBiQ324Y8DB6',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 02:07:44',
                'updated_at' => '2025-07-29 02:07:44',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            147 => 
            array (
                'id' => 157,
                'name' => 'Atif Gherib',
                'email' => 'gheribatif@yahoo.fr',
                'verified_at' => NULL,
                'password' => '$2y$12$ByBLjciDWsrKXYQao6laMeFrW4jdkflyw2QeUlwrPGPuawaDA/fly',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 08:07:49',
                'updated_at' => '2025-07-29 08:07:49',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            148 => 
            array (
                'id' => 158,
                'name' => 'STB',
                'email' => 'bet.stb@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$1tlOgEUV1woumwjb.6bFfONvdh1eHvRwxs9nkdhL5i6e2XIzYlVnu',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 08:36:16',
                'updated_at' => '2025-07-29 08:36:16',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            149 => 
            array (
                'id' => 159,
                'name' => 'talkarto',
                'email' => 'talkartohz@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$IDTdV.9zjZeKsGV.NArbkuK2eH0Uk4bL/mhr9fB.PkLYtc0Pam5uC',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 09:01:04',
                'updated_at' => '2025-07-29 09:01:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            150 => 
            array (
                'id' => 160,
                'name' => 'Hellal Merwan ',
                'email' => 'houriahh225@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$BAgsUlaze.9N8ympO52DQuuWV0/ocBkbDuunN5PJuPP8s7yxOFlIy',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 09:04:35',
                'updated_at' => '2025-07-29 09:04:35',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            151 => 
            array (
                'id' => 161,
                'name' => 'Zendagui Chahinez ',
                'email' => 'zendagui.ch@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$qNbdOt6O32x9wgr4XPcY3.gVnIZ1B0/RwZEI4MGvO6qY/uqQCC.Te',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 10:25:27',
                'updated_at' => '2025-07-29 10:25:27',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            152 => 
            array (
                'id' => 162,
                'name' => 'Asma toum',
                'email' => 'Asma.toumache1@mail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$XeOblaz.DNeVzdSC9qVz7ernm9sbsTscJ9UnbYgQ1BF4zBFua/W.G',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 10:36:21',
                'updated_at' => '2025-07-29 10:36:21',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            153 => 
            array (
                'id' => 163,
                'name' => 'Bet bonyan',
                'email' => 'bet.bonyan@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$KjH2dQAeJwFadiwDZhWUrOrLdmtuNRP7naGKGZksJA3Xwgu4YYoc2',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 11:53:37',
                'updated_at' => '2025-07-29 11:53:37',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            154 => 
            array (
                'id' => 164,
                'name' => 'Himeur soheyb ',
                'email' => 'Himeursoheyb@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$gUMcG.e1hSu1oi4yYUQ34OzGfvG9pIAW0sUGEr5C7YsjMgLvB/KhS',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 12:03:50',
                'updated_at' => '2025-07-29 12:03:50',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            155 => 
            array (
                'id' => 165,
                'name' => 'عمار دبابش ',
                'email' => 'zzazhza@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$2BOLRuNfUiWILtB3NoUBtO3pavt1nHtOe4Bti5oQaKIA.9ibUjrpK',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 12:30:04',
                'updated_at' => '2025-07-29 12:30:04',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            156 => 
            array (
                'id' => 166,
                'name' => 'Meriem Bouchikh ',
                'email' => 'bet.bouchikh@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$Jho.KtmQHpXMKUGOipfewORk.wAD6QUcApB7JxZiJ70QAR0PksLR6',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 15:35:41',
                'updated_at' => '2025-07-29 15:35:41',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
            157 => 
            array (
                'id' => 167,
                'name' => 'Fermas adel',
                'email' => 'fermas.adel79@gmail.com',
                'verified_at' => NULL,
                'password' => '$2y$12$mxwTa2ug.NpzAyXLoPqvquFaLxDAylU..6pyPuTSj5U1KwvSPkweC',
                'remember_token' => NULL,
                'created_at' => '2025-07-29 23:06:32',
                'updated_at' => '2025-07-29 23:06:32',
                'deleted_at' => NULL,
                'new_email' => NULL,
            ),
        ));
        
        
    }
}