version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ffp-events-app
    container_name: ffp-events-app
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=database
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - ffp-events-network

  queue:
    image: ffp-events-app
    container_name: ffp-events-queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - app
    networks:
      - ffp-events-network

  mysql:
    image: mysql:8.0
    container_name: ffp-events-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ffp-events-network

volumes:
  mysql_data:
    driver: local

networks:
  ffp-events-network:
    driver: bridge